using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SIRH.Web.Helpers
{
    public enum ETipoAccionesHelper
    {
        AnulacionP21 = 1,
        CeseFunciones = 2,
        CeseInterinidad = 3,
        DespidoCausa = 4,
        Incapacidad = 5,
        PermisoSueldoTotal = 6,
        PermisoSinSalario = 7,
        ProrrogaIncapacidad = 8,
        ProrrogaPermisoconSalario = 9,
        ProrrogaPermisosinSalario = 10,
        ProrrogaSuspTemporal = 11,
        Renuncia = 12,
        SupresionServicio = 13,
        SuspensionIndefinida = 14,
        SuspensionTemporal = 15,
        Vacaciones = 16,
        NombPlazoFijo = 20,
        NombPropiedad = 21,
        NombInterino = 22,
        ProrrogaNombramiento = 23,
        NombEspecial = 24,
        RegresoTrabajo = 25,
        Revaloracion = 27,
        ReinstalacionPropiedad = 28,
        ReinstalacionInterino = 29,
        AscensoPropiedad = 30,
        AscensoInterino = 31,
        AumentoAnual = 32,
        CambioCategoria = 36,
        CambioCodigo = 37,
        DescensoPropiedad = 38,
        DescensoInterino = 39,
        Modificacion = 44,
        PermisoSueldoParcial = 45,
        Permuta = 46,
        PermutaInterina = 47,
        ProrrogaAscenInterino = 48,
        ProrrogaDescInterino = 49,
        ProrrogaPermisoconSueldo = 50,
        ProrrogaPermutaInterino = 51,
        ProrrogaTrasladoInterino = 52,
        ReajusteSobresueldos = 53,
        Reasignacion = 54,
        RecargoFunciones = 55,
        RevaloracionReajuste = 56,
        Traslado = 57,
        TrasladoInterino = 58,
        Designacion = 59,
        ReajAprobProh = 60,
        ReajEliminProh = 61,
        ReajAprobDedicExc = 62,
        ReajEliminDedicExc = 63,
        ReajAprobDesarraigo = 64,
        ReajEliminDesarraigo = 65,
        ReajAprobRiesgoPolicial = 66,
        ReajEliminRiesgoPolicial = 67,
        ReajAprobDispon = 68,
        ReajEliminDisponib = 69,
        ReajCarreraProf = 70,
        ReajCursoBas = 71,
        ReajGradoAcadem = 72,
        ReajPorInstruc = 73,
        ReajPorQuinquenio = 74,
        RegresoPuestoPropiedad = 80,
        ReajAprobConsultaExterna = 81,
        ReajEliminConsultaExterna = 82,
        ReajAprobBonificAdicional = 83,
        ReajEliminBonificAdicional = 84,
        ModificFechaAA = 88,
        RestructPuesto = 90,
        CambioEspecialidad = 91,
        AddendumDedicExc = 94
    }
}
