//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Web.NombramientoLocal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NombramientoLocal.ICNombramientoService")]
    public interface ICNombramientoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/BuscarDatosParaNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/BuscarDatosParaNombramientoResponse")]
        SIRH.DTO.CBaseDTO[][] BuscarDatosParaNombramiento(string cedula, string codpuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/BuscarDatosParaNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/BuscarDatosParaNombramientoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarDatosParaNombramientoAsync(string cedula, string codpuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/DescargarCalificacionesCedula", ReplyAction="http://tempuri.org/ICNombramientoService/DescargarCalificacionesCedulaResponse")]
        SIRH.DTO.CBaseDTO[] DescargarCalificacionesCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/DescargarCalificacionesCedula", ReplyAction="http://tempuri.org/ICNombramientoService/DescargarCalificacionesCedulaResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> DescargarCalificacionesCedulaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/GuardarNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/GuardarNombramientoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoRubroDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CComponenteSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CObjetoGastoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPartidaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubPartidaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionReglaTecnicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoBorradorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalHistoricoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoVacacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CReintegroVacacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroVacacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePagoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDetallePagoViaticoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoViaticoRetroactivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CViaticoCorridoReintegroDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePagoGastoTrasporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDetallePagoGastoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CGastoTransporteReintegroDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAsignacionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBitacoraUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEliminacionViaticoCorridoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAsignacionGastoTransporteModificadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatMovimientoPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CComponentePresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBoletaPrestamoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CExpedienteFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFolioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTomoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNotificacionUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSalarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatDiaViaticoGastoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBitacoraIncidenciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncidenciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoIncidenciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistoricoPlanillaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionTemporalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionTemporalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEMUExfuncionarioDTO))]
        SIRH.DTO.CBaseDTO GuardarNombramiento(SIRH.DTO.CNombramientoDTO nombramiento, SIRH.DTO.CPuestoDTO puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/GuardarNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/GuardarNombramientoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> GuardarNombramientoAsync(SIRH.DTO.CNombramientoDTO nombramiento, SIRH.DTO.CPuestoDTO puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/CrearNombramientoInicial", ReplyAction="http://tempuri.org/ICNombramientoService/CrearNombramientoInicialResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoRubroDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CComponenteSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CObjetoGastoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPartidaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubPartidaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionReglaTecnicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoBorradorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalHistoricoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoVacacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CReintegroVacacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroVacacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePagoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDetallePagoViaticoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoViaticoRetroactivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CViaticoCorridoReintegroDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePagoGastoTrasporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDetallePagoGastoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CGastoTransporteReintegroDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAsignacionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBitacoraUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEliminacionViaticoCorridoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAsignacionGastoTransporteModificadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatMovimientoPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CComponentePresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBoletaPrestamoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CExpedienteFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFolioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTomoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNotificacionUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSalarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatDiaViaticoGastoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBitacoraIncidenciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncidenciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoIncidenciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistoricoPlanillaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionTemporalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionTemporalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEMUExfuncionarioDTO))]
        SIRH.DTO.CBaseDTO CrearNombramientoInicial(SIRH.DTO.CNombramientoDTO entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/CrearNombramientoInicial", ReplyAction="http://tempuri.org/ICNombramientoService/CrearNombramientoInicialResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> CrearNombramientoInicialAsync(SIRH.DTO.CNombramientoDTO entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/BuscarDatosRegistroNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/BuscarDatosRegistroNombramientoResponse")]
        SIRH.DTO.CBaseDTO[][] BuscarDatosRegistroNombramiento(string codpuesto, string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/BuscarDatosRegistroNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/BuscarDatosRegistroNombramientoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarDatosRegistroNombramientoAsync(string codpuesto, string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/ListarEstadosNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/ListarEstadosNombramientoResponse")]
        SIRH.DTO.CBaseDTO[] ListarEstadosNombramiento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/ListarEstadosNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/ListarEstadosNombramientoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ListarEstadosNombramientoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/DescargarNombramientoActualCedula", ReplyAction="http://tempuri.org/ICNombramientoService/DescargarNombramientoActualCedulaRespons" +
            "e")]
        SIRH.DTO.CBaseDTO[] DescargarNombramientoActualCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/DescargarNombramientoActualCedula", ReplyAction="http://tempuri.org/ICNombramientoService/DescargarNombramientoActualCedulaRespons" +
            "e")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> DescargarNombramientoActualCedulaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/BuscarHistorialNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/BuscarHistorialNombramientoResponse")]
        SIRH.DTO.CBaseDTO[][] BuscarHistorialNombramiento(SIRH.DTO.CFuncionarioDTO funcionario, System.DateTime[] fechasEmision, SIRH.DTO.CPuestoDTO puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/BuscarHistorialNombramiento", ReplyAction="http://tempuri.org/ICNombramientoService/BuscarHistorialNombramientoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarHistorialNombramientoAsync(SIRH.DTO.CFuncionarioDTO funcionario, System.DateTime[] fechasEmision, SIRH.DTO.CPuestoDTO puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/NombramientoPorCodigo", ReplyAction="http://tempuri.org/ICNombramientoService/NombramientoPorCodigoResponse")]
        SIRH.DTO.CBaseDTO[] NombramientoPorCodigo(int codigoNombramiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICNombramientoService/NombramientoPorCodigo", ReplyAction="http://tempuri.org/ICNombramientoService/NombramientoPorCodigoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> NombramientoPorCodigoAsync(int codigoNombramiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICNombramientoServiceChannel : SIRH.Web.NombramientoLocal.ICNombramientoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CNombramientoServiceClient : System.ServiceModel.ClientBase<SIRH.Web.NombramientoLocal.ICNombramientoService>, SIRH.Web.NombramientoLocal.ICNombramientoService {
        
        public CNombramientoServiceClient() {
        }
        
        public CNombramientoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CNombramientoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNombramientoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CNombramientoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIRH.DTO.CBaseDTO[][] BuscarDatosParaNombramiento(string cedula, string codpuesto) {
            return base.Channel.BuscarDatosParaNombramiento(cedula, codpuesto);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarDatosParaNombramientoAsync(string cedula, string codpuesto) {
            return base.Channel.BuscarDatosParaNombramientoAsync(cedula, codpuesto);
        }
        
        public SIRH.DTO.CBaseDTO[] DescargarCalificacionesCedula(string cedula) {
            return base.Channel.DescargarCalificacionesCedula(cedula);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> DescargarCalificacionesCedulaAsync(string cedula) {
            return base.Channel.DescargarCalificacionesCedulaAsync(cedula);
        }
        
        public SIRH.DTO.CBaseDTO GuardarNombramiento(SIRH.DTO.CNombramientoDTO nombramiento, SIRH.DTO.CPuestoDTO puesto) {
            return base.Channel.GuardarNombramiento(nombramiento, puesto);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> GuardarNombramientoAsync(SIRH.DTO.CNombramientoDTO nombramiento, SIRH.DTO.CPuestoDTO puesto) {
            return base.Channel.GuardarNombramientoAsync(nombramiento, puesto);
        }
        
        public SIRH.DTO.CBaseDTO CrearNombramientoInicial(SIRH.DTO.CNombramientoDTO entidad) {
            return base.Channel.CrearNombramientoInicial(entidad);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> CrearNombramientoInicialAsync(SIRH.DTO.CNombramientoDTO entidad) {
            return base.Channel.CrearNombramientoInicialAsync(entidad);
        }
        
        public SIRH.DTO.CBaseDTO[][] BuscarDatosRegistroNombramiento(string codpuesto, string cedula) {
            return base.Channel.BuscarDatosRegistroNombramiento(codpuesto, cedula);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarDatosRegistroNombramientoAsync(string codpuesto, string cedula) {
            return base.Channel.BuscarDatosRegistroNombramientoAsync(codpuesto, cedula);
        }
        
        public SIRH.DTO.CBaseDTO[] ListarEstadosNombramiento() {
            return base.Channel.ListarEstadosNombramiento();
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ListarEstadosNombramientoAsync() {
            return base.Channel.ListarEstadosNombramientoAsync();
        }
        
        public SIRH.DTO.CBaseDTO[] DescargarNombramientoActualCedula(string cedula) {
            return base.Channel.DescargarNombramientoActualCedula(cedula);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> DescargarNombramientoActualCedulaAsync(string cedula) {
            return base.Channel.DescargarNombramientoActualCedulaAsync(cedula);
        }
        
        public SIRH.DTO.CBaseDTO[][] BuscarHistorialNombramiento(SIRH.DTO.CFuncionarioDTO funcionario, System.DateTime[] fechasEmision, SIRH.DTO.CPuestoDTO puesto) {
            return base.Channel.BuscarHistorialNombramiento(funcionario, fechasEmision, puesto);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarHistorialNombramientoAsync(SIRH.DTO.CFuncionarioDTO funcionario, System.DateTime[] fechasEmision, SIRH.DTO.CPuestoDTO puesto) {
            return base.Channel.BuscarHistorialNombramientoAsync(funcionario, fechasEmision, puesto);
        }
        
        public SIRH.DTO.CBaseDTO[] NombramientoPorCodigo(int codigoNombramiento) {
            return base.Channel.NombramientoPorCodigo(codigoNombramiento);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> NombramientoPorCodigoAsync(int codigoNombramiento) {
            return base.Channel.NombramientoPorCodigoAsync(codigoNombramiento);
        }
    }
}
