using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.Serialization;


namespace SIRH.DTO
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CEstadoPedimentoDTO))]
    [KnownType(typeof(CDetalleCambioPedimentoDTO))]
    [KnownType(typeof(CResolucionPedimentoDTO))]
    [KnownType(typeof(CTipoResolucionPedimentoDTO))]
    [KnownType(typeof(CUsuarioDTO))]
    [KnownType(typeof(CFuncionarioDTO))]
    [KnownType(typeof(CActividadDTO))]
    [KnownType(typeof(CEstadoFuncionarioDTO))]
    [KnownType(typeof(CDetalleAccesoDTO))]
    [KnownType(typeof(CAreaDTO))]
    [KnownType(typeof(CCalificacionDTO))]
    [KnownType(typeof(CCalificacionNombramientoDTO))]
    [KnownType(typeof(CCalificacionNombramientoFuncionarioDTO))]
    [KnownType(typeof(CCantonDTO))]
    [KnownType(typeof(CCatEstadoCivilDTO))]
    [KnownType(typeof(CCatPermisoDTO))]
    [KnownType(typeof(CClaseDTO))]
    [KnownType(typeof(CCuentaBancariaDTO))]
    [KnownType(typeof(CDepartamentoDTO))]
    [KnownType(typeof(CDesgloseSalarialDTO))]
    [KnownType(typeof(CDetalleContratacionDTO))]
    [KnownType(typeof(CDetallePuestoDTO))]
    [KnownType(typeof(CDetalleTiempoExtraDTO))]
    [KnownType(typeof(CDireccionDTO))]
    [KnownType(typeof(CDireccionGeneralDTO))]
    [KnownType(typeof(CDistritoDTO))]
    [KnownType(typeof(CDivisionDTO))]
    [KnownType(typeof(CEntidadFinancieraDTO))]
    [KnownType(typeof(CEspecialidadDTO))]
    [KnownType(typeof(CEstadoNombramientoDTO))]
    [KnownType(typeof(CEstadoPuestoDTO))]
    [KnownType(typeof(CHistorialEstadoCivilDTO))]
    [KnownType(typeof(CIncentivoDTO))]
    [KnownType(typeof(CInformacionContactoDTO))]
    [KnownType(typeof(CMotivoMovimientoDTO))]
    [KnownType(typeof(CMovimientoPuestoDTO))]
    [KnownType(typeof(CNombramientoDTO))]
    [KnownType(typeof(COcupacionRealDTO))]
    [KnownType(typeof(CPerfilDTO))]
    [KnownType(typeof(CPerfilAccesoDTO))]
    [KnownType(typeof(CPresupuestoDTO))]
    [KnownType(typeof(CProgramaDTO))]
    [KnownType(typeof(CProvinciaDTO))]
    [KnownType(typeof(CPuestoDTO))]
    [KnownType(typeof(CRegistroTiempoExtraDTO))]
    [KnownType(typeof(CRelPresupuestoExtraDTO))]
    [KnownType(typeof(CRelPuestoUbicacionDTO))]
    [KnownType(typeof(CSeccionDTO))]
    [KnownType(typeof(CSubEspecialidadDTO))]
    [KnownType(typeof(CTipoContactoDTO))]
    [KnownType(typeof(CTipoExtraDTO))]
    [KnownType(typeof(CTipoIncentivoDTO))]
    [KnownType(typeof(CTipoJornadaDTO))]
    [KnownType(typeof(CTipoPuestoDTO))]
    [KnownType(typeof(CTipoUbicacionDTO))]
    [KnownType(typeof(CUbicacionAdministrativaDTO))]
    [KnownType(typeof(CUbicacionPuestoDTO))]
    [KnownType(typeof(CUbicacionRealDTO))]
    [KnownType(typeof(CErrorDTO))]
    [KnownType(typeof(CRespuestaDTO))]
    [KnownType(typeof(CCaucionDTO))]
    [KnownType(typeof(CMontoCaucionDTO))]
    [KnownType(typeof(CEntidadSegurosDTO))]
    [KnownType(typeof(CFormacionAcademicaDTO))]
    [KnownType(typeof(CCursoCapacitacionDTO))]
    [KnownType(typeof(CEntidadEducativaDTO))]
    [KnownType(typeof(CCursoGradoDTO))]
    [KnownType(typeof(CModalidadDTO))]
    [KnownType(typeof(CContenidoPresupuestarioDTO))]
    [KnownType(typeof(CPedimentoPuestoDTO))]
    [KnownType(typeof(CPrestamoPuestoDTO))]
    [KnownType(typeof(CEntidadAdscritaDTO))]
    [KnownType(typeof(CEntidadGubernamentalDTO))]
    [KnownType(typeof(CEstudioPuestoDTO))]
    [KnownType(typeof(CEstadoMovimientoPuestoDTO))]
    [KnownType(typeof(CAddendumPrestamoPuestoDTO))]
    [KnownType(typeof(CCaracteristicasPuestoDTO))]
    [KnownType(typeof(CFactorDTO))]
    [KnownType(typeof(CTituloFactorDTO))]
    [KnownType(typeof(CTareasPuestoDTO))]
    [KnownType(typeof(CRescisionDTO))]
    [KnownType(typeof(EEstadoDTO))]
    [KnownType(typeof(CPagoExtraordinarioDTO))]
    [KnownType(typeof(CTipoDeduccionDTO))]
    [KnownType(typeof(CCatalogoDeduccionDTO))]
    [KnownType(typeof(CTipoDiaDTO))]
    [KnownType(typeof(CCatalogoDiaDTO))]
    [KnownType(typeof(CUbicacionAsuetoDTO))]
    [KnownType(typeof(CPagoFeriadoDTO))]
    [KnownType(typeof(CDeduccionEfectuadaDTO))]
    [KnownType(typeof(CDiaPagadoDTO))]
    [KnownType(typeof(CEstadoTramiteDTO))]
    [KnownType(typeof(CCatalogoRemuneracionDTO))]
    [KnownType(typeof(CRemuneracionEfectuadaPFDTO))]
    [KnownType(typeof(CDispositivoDTO))]
    [KnownType(typeof(CEmpleadoDTO))]
    [KnownType(typeof(CEmpleadoDispositivoDTO))]
    [KnownType(typeof(CMotivoBajaDTO))]
    [KnownType(typeof(CContratoArrendamientoDTO))]
    [KnownType(typeof(CFacturaDesarraigoDTO))]
    [KnownType(typeof(CEstadoDesarraigoDTO))]
    [KnownType(typeof(CDetalleDesarraigoEliminacionDTO))]
    [KnownType(typeof(CDesarraigoDTO))]
    [KnownType(typeof(CCartaPresentacionDTO))]
    [KnownType(typeof(CHorarioRangoDTO))]
    [KnownType(typeof(CMarcacionesDTO))]
    [KnownType(typeof(CDetalleNombramientoDTO))]
    [KnownType(typeof(CTipoIncapacidadDTO))]
    [KnownType(typeof(CEntidadMedicaDTO))]
    [KnownType(typeof(CRegistroIncapacidadDTO))]
    [KnownType(typeof(CDetalleIncapacidadDTO))]
    [KnownType(typeof(CEscalaSalarialDTO))]
    [KnownType(typeof(CPeriodoEscalaSalarialDTO))]
    [KnownType(typeof(CDetalleCalificacionNombramientoDTO))]
    [KnownType(typeof(CCalificacionReglaTecnicaDTO))]
    [KnownType(typeof(CPeriodoCalificacionDTO))]
    [KnownType(typeof(CCatalogoPreguntaDTO))]
    [KnownType(typeof(CProcAlmacenadoDatosGeneralesDTO))]
    [KnownType(typeof(CProcAlmacenadoDTO))]
    [KnownType(typeof(CBorradorAccionPersonalDTO))]
    [KnownType(typeof(CDetalleBorradorAccionPersonalDTO))]
    [KnownType(typeof(CMovimientoBorradorAccionPersonalDTO))]
    [KnownType(typeof(CTipoAccionPersonalDTO))]
    [KnownType(typeof(CEstadoBorradorDTO))]
    [KnownType(typeof(CAccionPersonalDTO))]
    [KnownType(typeof(CAccionPersonalHistoricoDTO))]
    [KnownType(typeof(CDetalleAccionPersonalDTO))]
    [KnownType(typeof(CPeriodoVacacionesDTO))]
    [KnownType(typeof(CReintegroVacacionesDTO))]
    [KnownType(typeof(CRegistroVacacionesDTO))]
    [KnownType(typeof(CViaticoCorridoDTO))]
    [KnownType(typeof(CGastoTransporteDTO))]
    [KnownType(typeof(CDetalleDeduccionGastoTransporteDTO))]
    [KnownType(typeof(CDetalleDeduccionViaticoCorridoDTO))]
    [KnownType(typeof(CEstadoViaticoCorridoDTO))]
    [KnownType(typeof(CEstadoGastoTransporteDTO))]
    [KnownType(typeof(CDetalleAsignacionGastoTransporteDTO))]
    [KnownType(typeof(CMovimientoGastoTransporteDTO))]
    [KnownType(typeof(CMovimientoViaticoCorridoDTO))]
    [KnownType(typeof(CBitacoraUsuarioDTO))]
    [KnownType(typeof(CDetalleEliminacionViaticoCorridoGastoTransporteDTO))]
    [KnownType(typeof(CPagoViaticoCorridoDTO))]
    [KnownType(typeof(CDetallePagoViaticoCorridoDTO))]
    [KnownType(typeof(CTipoDetallePagoViaticoDTO))]
    [KnownType(typeof(CPagoGastoTransporteDTO))]
    [KnownType(typeof(CDetallePagoGastoTrasporteDTO))]
    [KnownType(typeof(CTipoDetallePagoGastoDTO))]
    [KnownType(typeof(CDetalleAsignacionGastoTransporteModificadaDTO))]
    [KnownType(typeof(CCatDiaViaticoGastoDTO))]
    [KnownType(typeof(CViaticoCorridoReintegroDTO))]
    [KnownType(typeof(CGastoTransporteReintegroDTO))]

    [KnownType(typeof(CCatMovimientoPresupuestoDTO))]
    [KnownType(typeof(CComponentePresupuestarioDTO))]
    [KnownType(typeof(CObjetoGastoDTO))]
    [KnownType(typeof(CPartidaDTO))]
    [KnownType(typeof(CSubPartidaDTO))]

    [KnownType(typeof(CBoletaPrestamoDTO))]
    [KnownType(typeof(CExpedienteFuncionarioDTO))]
    [KnownType(typeof(CFolioDTO))]
    [KnownType(typeof(CTomoDTO))]
    [KnownType(typeof(CNotificacionUsuarioDTO))]
    [KnownType(typeof(CSalarioDTO))]
    [KnownType(typeof(CComponenteSalarialDTO))]
    [KnownType(typeof(CDetallePuestoRubroDTO))]
    [KnownType(typeof(CCatDiaViaticoGastoDTO))]
    [KnownType(typeof(CBitacoraIncidenciaDTO))]
    [KnownType(typeof(CCatalogoIncidenciaDTO))]
    [KnownType(typeof(CIncidenciaDTO))]

    [KnownType(typeof(CDeduccionTemporalDTO))]
    [KnownType(typeof(CTipoDeduccionTemporalDTO))]
    [KnownType(typeof(CHistoricoPlanillaDTO))]
    [KnownType(typeof(CTipoDeduccionTemporalDTO))]
    [KnownType(typeof(CDeduccionTemporalDTO))]
    [KnownType(typeof(CEMUExfuncionarioDTO))]

    //EVALUACIÓN DESEMPEÑO NUEVO
    [KnownType(typeof(CActividadFuncionarioDTO))]
    [KnownType(typeof(CCalificacionCapacitacionDTO))]
    [KnownType(typeof(CCalificacionEncargadoDTO))]
    [KnownType(typeof(CCalificacionObservacionesDTO))]
    [KnownType(typeof(CCatMetaEstadoDTO))]
    [KnownType(typeof(CCatMetaPrioridadDTO))]
    [KnownType(typeof(CMetaIndividualCalificacionDTO))]
    [KnownType(typeof(CMetaIndividualEvidenciaDTO))]
    [KnownType(typeof(CMetaIndividualInformeDTO))]
    [KnownType(typeof(CMetaObjetivoCalificacionDTO))]
    [KnownType(typeof(CObjetivoCalificacionDTO))]
    [KnownType(typeof(CTipoIndicadorMetaDTO))]
    [KnownType(typeof(CTipoPoliticaPublicaDTO))]
    [KnownType(typeof(CDetalleCalificacionSeguimientoDTO))]

    [KnownType(typeof(CPrestacionLegalDTO))]
    [KnownType(typeof(CTipoPrestacionDTO))]
    [KnownType(typeof(CDetallePrestacionDTO))]
    [KnownType(typeof(CDetallePrestacionAfiliacionDTO))]
    [KnownType(typeof(CDetallePrestacionCuadroDTO))]
    [KnownType(typeof(CTipoPrestacionCuadroDTO))]

    [KnownType(typeof(COrdenMovimientoDTO))]
    [KnownType(typeof(COrdenMovimientoDeclaracionDTO))]
    [KnownType(typeof(CEstadoOrdenDTO))]
    [KnownType(typeof(CListaNombramientosActivosDTO))]

    //MANUAL CARGOS
    [KnownType(typeof(CCargoDTO))]
    [KnownType(typeof(CFactorClasificacionCargoDTO))]
    [KnownType(typeof(CRequerimientoEspecificoCargoDTO))]
    [KnownType(typeof(CResultadoCargoDTO))]
    [KnownType(typeof(CActividadResultadoCargoDTO))]
    [KnownType(typeof(CCompetenciaTransversalCargoDTO))]
    [KnownType(typeof(CComportamientoTransversalDTO))]
    [KnownType(typeof(CEvidenciaComportamientoTransversalDTO))]
    [KnownType(typeof(CCompetenciaGrupoOcupacionalDTO))]
    [KnownType(typeof(CComportamientoGrupoOcupacionalDTO))]
    [KnownType(typeof(CEvidenciaGrupoOcupacionalDTO))]

    [KnownType(typeof(CEMUExfuncionarioDTO))]
    [KnownType(typeof(CNotificacionUsuarioDTO))]

    //MANUAL CARGOS
    [KnownType(typeof(CCargoDTO))]
    [KnownType(typeof(CFactorClasificacionCargoDTO))]
    [KnownType(typeof(CRequerimientoEspecificoCargoDTO))]
    [KnownType(typeof(CResultadoCargoDTO))]
    [KnownType(typeof(CActividadResultadoCargoDTO))]
    [KnownType(typeof(CCompetenciaTransversalCargoDTO))]
    [KnownType(typeof(CComportamientoTransversalDTO))]
    [KnownType(typeof(CEvidenciaComportamientoTransversalDTO))]
    [KnownType(typeof(CCompetenciaGrupoOcupacionalDTO))]
    [KnownType(typeof(CComportamientoGrupoOcupacionalDTO))]
    [KnownType(typeof(CEvidenciaGrupoOcupacionalDTO))]

    //EVALUACIÓN DESEMPEÑO NUEVO
    [KnownType(typeof(CActividadFuncionarioDTO))]
    [KnownType(typeof(CCalificacionCapacitacionDTO))]
    [KnownType(typeof(CCalificacionEncargadoDTO))]
    [KnownType(typeof(CCalificacionObservacionesDTO))]
    [KnownType(typeof(CCatMetaEstadoDTO))]
    [KnownType(typeof(CCatMetaPrioridadDTO))]
    [KnownType(typeof(CMetaIndividualCalificacionDTO))]
    [KnownType(typeof(CMetaIndividualEvidenciaDTO))]
    [KnownType(typeof(CMetaIndividualInformeDTO))]
    [KnownType(typeof(CMetaObjetivoCalificacionDTO))]
    [KnownType(typeof(CObjetivoCalificacionDTO))]
    [KnownType(typeof(CTipoIndicadorMetaDTO))]
    [KnownType(typeof(CTipoPoliticaPublicaDTO))]

    [KnownType(typeof(CPrestacionLegalDTO))]
    [KnownType(typeof(CTipoPrestacionDTO))]
    [KnownType(typeof(CDetallePrestacionDTO))]
    [KnownType(typeof(CDetallePrestacionAfiliacionDTO))]
    [KnownType(typeof(CDetallePrestacionCuadroDTO))]
    [KnownType(typeof(CTipoPrestacionCuadroDTO))]

    [KnownType(typeof(COrdenMovimientoDTO))]
    [KnownType(typeof(COrdenMovimientoDeclaracionDTO))]
    [KnownType(typeof(CEstadoOrdenDTO))]

    // PLANIFICACIÓN
    [KnownType(typeof(CCatCampoDTO))]
    [KnownType(typeof(CSolicitudCambioDTO))]
    [KnownType(typeof(CDetalleSolicitudCambioDTO))]
    [KnownType(typeof(CListaNombramientosActivosDTO))]

    [KnownType(typeof(CParametrosDTO))]

    [KnownType(typeof(CTemp_EnviarCorreoDTO))]

    [KnownType(typeof(CCarreraProfesionalDTO))]
    [KnownType(typeof(CCursoDTO))]
    [KnownType(typeof(CDetallePuntosDTO))]
    [KnownType(typeof(CPuntosDTO))]

    [KnownType(typeof(CDecretoDTO))]

    public class CBaseDTO
    {
        [DataMember]
        public int IdEntidad { get; set; }
        [DataMember]
        public string Mensaje { get; set; }
    }
}
