//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public int IdDepartamento { get; set; }
        public string CodigoDepartamento { get; set; }
        public string Descripcion { get; set; }
        public int CodigoEnPunto { get; set; }
    }
}
