//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaParametros
    {
        public int IdEmpresa { get; set; }
        public Nullable<short> Doblemarcaje { get; set; }
        public Nullable<short> tiempodoblemarcaje { get; set; }
        public Nullable<short> descuentamatutino { get; set; }
        public Nullable<short> descuentavespertino { get; set; }
        public Nullable<short> descuentaalimentacion { get; set; }
        public string lviniciadoble { get; set; }
        public string lvfindoble { get; set; }
        public string siniciadoble { get; set; }
        public string sfindoble { get; set; }
        public string diniciadoble { get; set; }
        public string dfindoble { get; set; }
    }
}
