//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int IdEmpresa { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public string RepresentanteLegal { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<short> EntradaTarde { get; set; }
        public Nullable<short> RenumeriacionHoraExtra { get; set; }
        public Nullable<short> PoliticaHoraExtra { get; set; }
        public string NombreDB { get; set; }
        public string PathDB { get; set; }
        public string NombreLogo { get; set; }
        public Nullable<short> GeneraCodigo { get; set; }
        public Nullable<short> Verifica { get; set; }
        public string Usuairo { get; set; }
        public string PassWord { get; set; }
        public Nullable<short> AutorizacionHorasExtras { get; set; }
        public Nullable<short> TomarHorasExtras { get; set; }
        public string FaltantedeMarca { get; set; }
        public short MarcarESHE { get; set; }
        public string Prefijo { get; set; }
        public decimal Correlativo { get; set; }
        public byte[] ImageLogo { get; set; }
        public int PrioridadProcesoMarca { get; set; }
        public int AgregaMarcaBlanco { get; set; }
        public int ProcesoMarcas { get; set; }
    }
}
