//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioHD
    {
        public int IdHorario { get; set; }
        public string NombreHorario { get; set; }
        public string Codigo { get; set; }
        public int TiempoMaxDentroOf { get; set; }
        public int CodigoEnPunto { get; set; }
        public string DescansoMatituno { get; set; }
        public string DescansoVespertino { get; set; }
        public short MarcaAlimentacion { get; set; }
        public int PosicionTurno1 { get; set; }
        public int PosicionTurno2 { get; set; }
    }
}
