//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepEntradaSalida
    {
        public string CodigoEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime EntradaJornada1 { get; set; }
        public System.DateTime SalidaJornada1 { get; set; }
        public System.DateTime EntradaJornada2 { get; set; }
        public System.DateTime SalidaJornada2 { get; set; }
        public System.DateTime EntradaJornada3 { get; set; }
        public System.DateTime SalidaJornada3 { get; set; }
        public System.DateTime EntradaJornada4 { get; set; }
        public System.DateTime SalidaJornada4 { get; set; }
        public System.DateTime TotalHorasDia { get; set; }
        public System.DateTime Discrepancia { get; set; }
    }
}
