//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepHoraExtra
    {
        public string CodigoEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime HoraEntradaJ1 { get; set; }
        public System.DateTime HoraSalidaJ1 { get; set; }
        public System.DateTime HoraEntradaJ2 { get; set; }
        public System.DateTime HoraSalidaJ2 { get; set; }
        public System.DateTime HoraEntradaJ3 { get; set; }
        public System.DateTime HoraSalidaJ3 { get; set; }
        public System.DateTime HoraEntradaJ4 { get; set; }
        public System.DateTime HoraSalidaJ4 { get; set; }
        public System.DateTime HoraExtraNormal { get; set; }
        public System.DateTime HoraExtraNormalNoLaboral { get; set; }
        public System.DateTime HoraExtraDiaFeriado { get; set; }
    }
}
