//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepIncidenciasGen
    {
        public string CodigoEmpleado { get; set; }
        public string TipoEntradaSalida { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Hora { get; set; }
    }
}
