//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablasDT
    {
        public int IdCampo { get; set; }
        public int IdTabla { get; set; }
        public int CorrelaTabla { get; set; }
        public string NombreCampo { get; set; }
        public int TipoDato { get; set; }
        public decimal Longitud { get; set; }
        public short Nulo { get; set; }
    }
}
