//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MarcasRelojes
    {
        public System.DateTime Fecha { get; set; }
        public string Dispositivo { get; set; }
        public string CodEmpleado { get; set; }
        public string CodBiometrica { get; set; }
        public string Nombre { get; set; }
        public string hr { get; set; }
        public string mi { get; set; }
        public string sg { get; set; }
        public string Depto { get; set; }
        public string Puesto { get; set; }
    }
}
