//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.DatosMarcasReloj
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaTiempoDT
    {
        public int IdZonaTiempo { get; set; }
        public short Intervalo { get; set; }
        public System.DateTime HoraInicial { get; set; }
        public System.DateTime HoraFinal { get; set; }
        public short Lunes { get; set; }
        public short Martes { get; set; }
        public short Miercoles { get; set; }
        public short Jueves { get; set; }
        public short Viernes { get; set; }
        public short Sabado { get; set; }
        public short Domingo { get; set; }
    }
}
