//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Web.ServicioCalificacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCalificacion.ICCalificacionService")]
    public interface ICCalificacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/GuardarCalificacion", ReplyAction="http://tempuri.org/ICCalificacionService/GuardarCalificacionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        SIRH.DTO.CBaseDTO GuardarCalificacion(string cedula, SIRH.DTO.CCalificacionDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/GuardarCalificacion", ReplyAction="http://tempuri.org/ICCalificacionService/GuardarCalificacionResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> GuardarCalificacionAsync(string cedula, SIRH.DTO.CCalificacionDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/CargarCalificaciones", ReplyAction="http://tempuri.org/ICCalificacionService/CargarCalificacionesResponse")]
        SIRH.DTO.CBaseDTO[] CargarCalificaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/CargarCalificaciones", ReplyAction="http://tempuri.org/ICCalificacionService/CargarCalificacionesResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> CargarCalificacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/DescargarCalificacionesCedula", ReplyAction="http://tempuri.org/ICCalificacionService/DescargarCalificacionesCedulaResponse")]
        SIRH.DTO.CBaseDTO[] DescargarCalificacionesCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/DescargarCalificacionesCedula", ReplyAction="http://tempuri.org/ICCalificacionService/DescargarCalificacionesCedulaResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> DescargarCalificacionesCedulaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/GuardarCalificacionFuncionario", ReplyAction="http://tempuri.org/ICCalificacionService/GuardarCalificacionFuncionarioResponse")]
        SIRH.DTO.CBaseDTO[] GuardarCalificacionFuncionario(SIRH.DTO.CCalificacionNombramientoDTO CalificacionCN, SIRH.DTO.CDetalleCalificacionNombramientoDTO DetalleDCN, SIRH.DTO.CDetalleEvaluacionDTO[] DetalleE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/GuardarCalificacionFuncionario", ReplyAction="http://tempuri.org/ICCalificacionService/GuardarCalificacionFuncionarioResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> GuardarCalificacionFuncionarioAsync(SIRH.DTO.CCalificacionNombramientoDTO CalificacionCN, SIRH.DTO.CDetalleCalificacionNombramientoDTO DetalleDCN, SIRH.DTO.CDetalleEvaluacionDTO[] DetalleE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/ObtenerCalificacion", ReplyAction="http://tempuri.org/ICCalificacionService/ObtenerCalificacionResponse")]
        SIRH.DTO.CBaseDTO[] ObtenerCalificacion(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/ObtenerCalificacion", ReplyAction="http://tempuri.org/ICCalificacionService/ObtenerCalificacionResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ObtenerCalificacionAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/DescargarDatosCC", ReplyAction="http://tempuri.org/ICCalificacionService/DescargarDatosCCResponse")]
        SIRH.DTO.CProcAlmacenadoDTO[] DescargarDatosCC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/DescargarDatosCC", ReplyAction="http://tempuri.org/ICCalificacionService/DescargarDatosCCResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CProcAlmacenadoDTO[]> DescargarDatosCCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/DescargarDatosGEvaluacion", ReplyAction="http://tempuri.org/ICCalificacionService/DescargarDatosGEvaluacionResponse")]
        SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO[] DescargarDatosGEvaluacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/DescargarDatosGEvaluacion", ReplyAction="http://tempuri.org/ICCalificacionService/DescargarDatosGEvaluacionResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO[]> DescargarDatosGEvaluacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/AgregarDetalleCalificacionNombramiento", ReplyAction="http://tempuri.org/ICCalificacionService/AgregarDetalleCalificacionNombramientoRe" +
            "sponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        SIRH.DTO.CBaseDTO AgregarDetalleCalificacionNombramiento(int idCalificacion, SIRH.DTO.CDetalleCalificacionNombramientoDTO detalleNombramiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/AgregarDetalleCalificacionNombramiento", ReplyAction="http://tempuri.org/ICCalificacionService/AgregarDetalleCalificacionNombramientoRe" +
            "sponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> AgregarDetalleCalificacionNombramientoAsync(int idCalificacion, SIRH.DTO.CDetalleCalificacionNombramientoDTO detalleNombramiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/EditarDetalleCalificacionNombramiento", ReplyAction="http://tempuri.org/ICCalificacionService/EditarDetalleCalificacionNombramientoRes" +
            "ponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        SIRH.DTO.CBaseDTO EditarDetalleCalificacionNombramiento(int detalleNombramiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/EditarDetalleCalificacionNombramiento", ReplyAction="http://tempuri.org/ICCalificacionService/EditarDetalleCalificacionNombramientoRes" +
            "ponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> EditarDetalleCalificacionNombramientoAsync(int detalleNombramiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/ListarCalificaciones", ReplyAction="http://tempuri.org/ICCalificacionService/ListarCalificacionesResponse")]
        SIRH.DTO.CBaseDTO[][] ListarCalificaciones(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/ListarCalificaciones", ReplyAction="http://tempuri.org/ICCalificacionService/ListarCalificacionesResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> ListarCalificacionesAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/AgregarDetalleEvaluacion", ReplyAction="http://tempuri.org/ICCalificacionService/AgregarDetalleEvaluacionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        SIRH.DTO.CBaseDTO AgregarDetalleEvaluacion(SIRH.DTO.CDetalleCalificacionNombramientoDTO idDetalleCN, SIRH.DTO.CCatalogoPreguntaDTO idPregunta, SIRH.DTO.CDetalleEvaluacionDTO detalleE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/AgregarDetalleEvaluacion", ReplyAction="http://tempuri.org/ICCalificacionService/AgregarDetalleEvaluacionResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> AgregarDetalleEvaluacionAsync(SIRH.DTO.CDetalleCalificacionNombramientoDTO idDetalleCN, SIRH.DTO.CCatalogoPreguntaDTO idPregunta, SIRH.DTO.CDetalleEvaluacionDTO detalleE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/AgregarPregunta", ReplyAction="http://tempuri.org/ICCalificacionService/AgregarPreguntaResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        SIRH.DTO.CBaseDTO AgregarPregunta(SIRH.DTO.CCatalogoPreguntaDTO pregunta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/AgregarPregunta", ReplyAction="http://tempuri.org/ICCalificacionService/AgregarPreguntaResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> AgregarPreguntaAsync(SIRH.DTO.CCatalogoPreguntaDTO pregunta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/EditarPregunta", ReplyAction="http://tempuri.org/ICCalificacionService/EditarPreguntaResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        SIRH.DTO.CBaseDTO EditarPregunta(SIRH.DTO.CCatalogoPreguntaDTO pregunta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/EditarPregunta", ReplyAction="http://tempuri.org/ICCalificacionService/EditarPreguntaResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> EditarPreguntaAsync(SIRH.DTO.CCatalogoPreguntaDTO pregunta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/ObtenerPreguntas", ReplyAction="http://tempuri.org/ICCalificacionService/ObtenerPreguntasResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        SIRH.DTO.CBaseDTO ObtenerPreguntas(int codPregunta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/ObtenerPreguntas", ReplyAction="http://tempuri.org/ICCalificacionService/ObtenerPreguntasResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> ObtenerPreguntasAsync(int codPregunta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/ListarPreguntas", ReplyAction="http://tempuri.org/ICCalificacionService/ListarPreguntasResponse")]
        SIRH.DTO.CBaseDTO[] ListarPreguntas(int tipoFormulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCalificacionService/ListarPreguntas", ReplyAction="http://tempuri.org/ICCalificacionService/ListarPreguntasResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ListarPreguntasAsync(int tipoFormulario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICCalificacionServiceChannel : SIRH.Web.ServicioCalificacion.ICCalificacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCalificacionServiceClient : System.ServiceModel.ClientBase<SIRH.Web.ServicioCalificacion.ICCalificacionService>, SIRH.Web.ServicioCalificacion.ICCalificacionService {
        
        public CCalificacionServiceClient() {
        }
        
        public CCalificacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCalificacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCalificacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCalificacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIRH.DTO.CBaseDTO GuardarCalificacion(string cedula, SIRH.DTO.CCalificacionDTO item) {
            return base.Channel.GuardarCalificacion(cedula, item);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> GuardarCalificacionAsync(string cedula, SIRH.DTO.CCalificacionDTO item) {
            return base.Channel.GuardarCalificacionAsync(cedula, item);
        }
        
        public SIRH.DTO.CBaseDTO[] CargarCalificaciones() {
            return base.Channel.CargarCalificaciones();
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> CargarCalificacionesAsync() {
            return base.Channel.CargarCalificacionesAsync();
        }
        
        public SIRH.DTO.CBaseDTO[] DescargarCalificacionesCedula(string cedula) {
            return base.Channel.DescargarCalificacionesCedula(cedula);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> DescargarCalificacionesCedulaAsync(string cedula) {
            return base.Channel.DescargarCalificacionesCedulaAsync(cedula);
        }
        
        public SIRH.DTO.CBaseDTO[] GuardarCalificacionFuncionario(SIRH.DTO.CCalificacionNombramientoDTO CalificacionCN, SIRH.DTO.CDetalleCalificacionNombramientoDTO DetalleDCN, SIRH.DTO.CDetalleEvaluacionDTO[] DetalleE) {
            return base.Channel.GuardarCalificacionFuncionario(CalificacionCN, DetalleDCN, DetalleE);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> GuardarCalificacionFuncionarioAsync(SIRH.DTO.CCalificacionNombramientoDTO CalificacionCN, SIRH.DTO.CDetalleCalificacionNombramientoDTO DetalleDCN, SIRH.DTO.CDetalleEvaluacionDTO[] DetalleE) {
            return base.Channel.GuardarCalificacionFuncionarioAsync(CalificacionCN, DetalleDCN, DetalleE);
        }
        
        public SIRH.DTO.CBaseDTO[] ObtenerCalificacion(int codigo) {
            return base.Channel.ObtenerCalificacion(codigo);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ObtenerCalificacionAsync(int codigo) {
            return base.Channel.ObtenerCalificacionAsync(codigo);
        }
        
        public SIRH.DTO.CProcAlmacenadoDTO[] DescargarDatosCC() {
            return base.Channel.DescargarDatosCC();
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CProcAlmacenadoDTO[]> DescargarDatosCCAsync() {
            return base.Channel.DescargarDatosCCAsync();
        }
        
        public SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO[] DescargarDatosGEvaluacion() {
            return base.Channel.DescargarDatosGEvaluacion();
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO[]> DescargarDatosGEvaluacionAsync() {
            return base.Channel.DescargarDatosGEvaluacionAsync();
        }
        
        public SIRH.DTO.CBaseDTO AgregarDetalleCalificacionNombramiento(int idCalificacion, SIRH.DTO.CDetalleCalificacionNombramientoDTO detalleNombramiento) {
            return base.Channel.AgregarDetalleCalificacionNombramiento(idCalificacion, detalleNombramiento);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> AgregarDetalleCalificacionNombramientoAsync(int idCalificacion, SIRH.DTO.CDetalleCalificacionNombramientoDTO detalleNombramiento) {
            return base.Channel.AgregarDetalleCalificacionNombramientoAsync(idCalificacion, detalleNombramiento);
        }
        
        public SIRH.DTO.CBaseDTO EditarDetalleCalificacionNombramiento(int detalleNombramiento) {
            return base.Channel.EditarDetalleCalificacionNombramiento(detalleNombramiento);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> EditarDetalleCalificacionNombramientoAsync(int detalleNombramiento) {
            return base.Channel.EditarDetalleCalificacionNombramientoAsync(detalleNombramiento);
        }
        
        public SIRH.DTO.CBaseDTO[][] ListarCalificaciones(string cedula) {
            return base.Channel.ListarCalificaciones(cedula);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> ListarCalificacionesAsync(string cedula) {
            return base.Channel.ListarCalificacionesAsync(cedula);
        }
        
        public SIRH.DTO.CBaseDTO AgregarDetalleEvaluacion(SIRH.DTO.CDetalleCalificacionNombramientoDTO idDetalleCN, SIRH.DTO.CCatalogoPreguntaDTO idPregunta, SIRH.DTO.CDetalleEvaluacionDTO detalleE) {
            return base.Channel.AgregarDetalleEvaluacion(idDetalleCN, idPregunta, detalleE);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> AgregarDetalleEvaluacionAsync(SIRH.DTO.CDetalleCalificacionNombramientoDTO idDetalleCN, SIRH.DTO.CCatalogoPreguntaDTO idPregunta, SIRH.DTO.CDetalleEvaluacionDTO detalleE) {
            return base.Channel.AgregarDetalleEvaluacionAsync(idDetalleCN, idPregunta, detalleE);
        }
        
        public SIRH.DTO.CBaseDTO AgregarPregunta(SIRH.DTO.CCatalogoPreguntaDTO pregunta) {
            return base.Channel.AgregarPregunta(pregunta);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> AgregarPreguntaAsync(SIRH.DTO.CCatalogoPreguntaDTO pregunta) {
            return base.Channel.AgregarPreguntaAsync(pregunta);
        }
        
        public SIRH.DTO.CBaseDTO EditarPregunta(SIRH.DTO.CCatalogoPreguntaDTO pregunta) {
            return base.Channel.EditarPregunta(pregunta);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> EditarPreguntaAsync(SIRH.DTO.CCatalogoPreguntaDTO pregunta) {
            return base.Channel.EditarPreguntaAsync(pregunta);
        }
        
        public SIRH.DTO.CBaseDTO ObtenerPreguntas(int codPregunta) {
            return base.Channel.ObtenerPreguntas(codPregunta);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> ObtenerPreguntasAsync(int codPregunta) {
            return base.Channel.ObtenerPreguntasAsync(codPregunta);
        }
        
        public SIRH.DTO.CBaseDTO[] ListarPreguntas(int tipoFormulario) {
            return base.Channel.ListarPreguntas(tipoFormulario);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ListarPreguntasAsync(int tipoFormulario) {
            return base.Channel.ListarPreguntasAsync(tipoFormulario);
        }
    }
}
