//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Web.TipoAccionPersonalLocal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TipoAccionPersonalLocal.ICTipoAccionPersonalService")]
    public interface ICTipoAccionPersonalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoAccionPersonalService/RetornarTipos", ReplyAction="http://tempuri.org/ICTipoAccionPersonalService/RetornarTiposResponse")]
        SIRH.DTO.CBaseDTO[] RetornarTipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoAccionPersonalService/RetornarTipos", ReplyAction="http://tempuri.org/ICTipoAccionPersonalService/RetornarTiposResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> RetornarTiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoAccionPersonalService/ObtenerTipo", ReplyAction="http://tempuri.org/ICTipoAccionPersonalService/ObtenerTipoResponse")]
        SIRH.DTO.CBaseDTO[] ObtenerTipo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoAccionPersonalService/ObtenerTipo", ReplyAction="http://tempuri.org/ICTipoAccionPersonalService/ObtenerTipoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ObtenerTipoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoAccionPersonalService/AgregarTipo", ReplyAction="http://tempuri.org/ICTipoAccionPersonalService/AgregarTipoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoAccionPersonalDTO))]
        SIRH.DTO.CBaseDTO AgregarTipo(SIRH.DTO.CTipoAccionPersonalDTO tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoAccionPersonalService/AgregarTipo", ReplyAction="http://tempuri.org/ICTipoAccionPersonalService/AgregarTipoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> AgregarTipoAsync(SIRH.DTO.CTipoAccionPersonalDTO tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoAccionPersonalService/EditarTipo", ReplyAction="http://tempuri.org/ICTipoAccionPersonalService/EditarTipoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoAccionPersonalDTO))]
        SIRH.DTO.CBaseDTO EditarTipo(SIRH.DTO.CTipoAccionPersonalDTO tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoAccionPersonalService/EditarTipo", ReplyAction="http://tempuri.org/ICTipoAccionPersonalService/EditarTipoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> EditarTipoAsync(SIRH.DTO.CTipoAccionPersonalDTO tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICTipoAccionPersonalServiceChannel : SIRH.Web.TipoAccionPersonalLocal.ICTipoAccionPersonalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CTipoAccionPersonalServiceClient : System.ServiceModel.ClientBase<SIRH.Web.TipoAccionPersonalLocal.ICTipoAccionPersonalService>, SIRH.Web.TipoAccionPersonalLocal.ICTipoAccionPersonalService {
        
        public CTipoAccionPersonalServiceClient() {
        }
        
        public CTipoAccionPersonalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CTipoAccionPersonalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTipoAccionPersonalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTipoAccionPersonalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIRH.DTO.CBaseDTO[] RetornarTipos() {
            return base.Channel.RetornarTipos();
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> RetornarTiposAsync() {
            return base.Channel.RetornarTiposAsync();
        }
        
        public SIRH.DTO.CBaseDTO[] ObtenerTipo(int codigo) {
            return base.Channel.ObtenerTipo(codigo);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ObtenerTipoAsync(int codigo) {
            return base.Channel.ObtenerTipoAsync(codigo);
        }
        
        public SIRH.DTO.CBaseDTO AgregarTipo(SIRH.DTO.CTipoAccionPersonalDTO tipo) {
            return base.Channel.AgregarTipo(tipo);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> AgregarTipoAsync(SIRH.DTO.CTipoAccionPersonalDTO tipo) {
            return base.Channel.AgregarTipoAsync(tipo);
        }
        
        public SIRH.DTO.CBaseDTO EditarTipo(SIRH.DTO.CTipoAccionPersonalDTO tipo) {
            return base.Channel.EditarTipo(tipo);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> EditarTipoAsync(SIRH.DTO.CTipoAccionPersonalDTO tipo) {
            return base.Channel.EditarTipoAsync(tipo);
        }
    }
}
