
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class ActividadResultadoCargo
{

    public int PK_ActividadResultadoCargo { get; set; }

    public string DesActividadResultadoCargo { get; set; }

    public Nullable<int> FK_ResultadoCargo { get; set; }



    public virtual ResultadoCargo ResultadoCargo { get; set; }

}

}
