
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class ActividadMeta
{

    public ActividadMeta()
    {

        this.EjecutorActividad = new HashSet<EjecutorActividad>();

    }


    public int PK_Actividades { get; set; }

    public Nullable<int> FK_Meta { get; set; }

    public string DesResultadoEsperado { get; set; }

    public string DesResultadoObtenido { get; set; }

    public Nullable<System.DateTime> FecInicio { get; set; }

    public Nullable<System.DateTime> FecFinal { get; set; }

    public string DesAccion { get; set; }

    public Nullable<int> IndEstado { get; set; }

    public string DesObservaciones { get; set; }



    public virtual MetaObjetivoInstitucional MetaObjetivoInstitucional { get; set; }

    public virtual ICollection<EjecutorActividad> EjecutorActividad { get; set; }

}

}
