
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class AddendumPrestamoPuesto
{

    public int PK_AddendumPrestamoPuesto { get; set; }

    public Nullable<int> FK_PrestamoPuesto { get; set; }

    public string NumAddendum { get; set; }

    public Nullable<System.DateTime> FecRige { get; set; }

    public Nullable<System.DateTime> FecFin { get; set; }



    public virtual PrestamoPuesto PrestamoPuesto { get; set; }

}

}
