
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class C_EMU_Vacaciones_Saldo
{

    public int ID { get; set; }

    public string CEDULA { get; set; }

    public string PERI_VACA { get; set; }

    public string SALDO { get; set; }

    public string FRAC_VACA { get; set; }

    public string DOCU_VACA { get; set; }

}

}
