
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class C_EMU_HistoricoPlanilla_oldie
{

    public int ID { get; set; }

    public string CEDULA { get; set; }

    public string CODIGO_PRESUPUESTARIO { get; set; }

    public string CATEGORIA { get; set; }

    public string NUMERO_PUESTO { get; set; }

    public string CLASE_PUESTO { get; set; }

    public Nullable<decimal> BASE { get; set; }

    public Nullable<decimal> AUMENTOS { get; set; }

    public Nullable<decimal> GRUPO { get; set; }

    public Nullable<decimal> SOBRESUELDOS { get; set; }

    public Nullable<decimal> PROHIBICION { get; set; }

    public Nullable<decimal> RECARGO { get; set; }

    public Nullable<decimal> EMBARGO { get; set; }

    public Nullable<decimal> OTROS { get; set; }

    public Nullable<decimal> PSS_SUS { get; set; }

    public Nullable<decimal> SAL_MENSUAL { get; set; }

    public Nullable<decimal> TOT_SALARIO { get; set; }

    public string RUTA { get; set; }

    public string FECHA_CORRIDA { get; set; }

    public string FECHA_PERIODO { get; set; }

    public string NUMERO_GIRO { get; set; }

    public Nullable<decimal> ZONAJE { get; set; }

    public Nullable<decimal> CANT_PUNTOS { get; set; }

    public Nullable<decimal> PORC_DEDICACION { get; set; }

    public Nullable<decimal> PORC_PELIGROSIDAD { get; set; }

    public Nullable<decimal> PORC_PROHIBICION { get; set; }

    public Nullable<decimal> PORC_QUINQUENIO { get; set; }

    public Nullable<decimal> PORC_DISPONIBILIDAD { get; set; }

    public Nullable<decimal> PORC_GRADO_ACADEMICO { get; set; }

    public Nullable<decimal> PORC_RIESGO_POLICIAL { get; set; }

    public Nullable<decimal> PORC_CURSO_BASICO { get; set; }

    public Nullable<decimal> PORC_INSTRUCCION { get; set; }

    public Nullable<decimal> PORC_BONIFICACION { get; set; }

    public Nullable<decimal> PORC_CONSULTA_EXTERNA { get; set; }

    public Nullable<decimal> DEDICACION_EXCLUSIVA { get; set; }

    public Nullable<decimal> PELIGROSIDAD { get; set; }

    public Nullable<decimal> GRADO_ACADEMICO { get; set; }

    public Nullable<decimal> DISPONIBILIDAD { get; set; }

    public Nullable<decimal> QUINQUENIO { get; set; }

    public Nullable<decimal> RIESGO_POLICIAL { get; set; }

    public Nullable<decimal> CURSO_BASICO { get; set; }

    public Nullable<decimal> INSTRUCCION { get; set; }

    public Nullable<decimal> CONSULTA_EXTERNA { get; set; }

    public Nullable<decimal> DESARRAIGO { get; set; }

    public Nullable<decimal> BONIFICACION { get; set; }

    public Nullable<decimal> OTROS_INCENTIVOS { get; set; }

    public string DIVISION { get; set; }

    public string DIRECCION { get; set; }

    public string DEPARTAMENTO { get; set; }

    public string SECCION { get; set; }

}

}
