
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class C_EMU_Puntos
{

    public int ID { get; set; }

    public string Nombre { get; set; }

    public string Cedula { get; set; }

    public Nullable<decimal> TotalPuntos { get; set; }

    public Nullable<int> ValorPunto { get; set; }

    public Nullable<int> AnnoExpPR { get; set; }

    public Nullable<int> Aprovechamiento { get; set; }

    public Nullable<int> Participacion { get; set; }

    public Nullable<int> ParticipacionInstruccion { get; set; }

    public string CalificacionServicio { get; set; }

    public Nullable<decimal> HorasAprovechamiento { get; set; }

    public Nullable<decimal> HorasParticipacion { get; set; }

    public Nullable<decimal> HorasInstruccion { get; set; }

    public Nullable<decimal> PtosGrado { get; set; }

    public Nullable<decimal> PtosAprovechamiento { get; set; }

    public Nullable<decimal> PtosExpPR { get; set; }

    public Nullable<decimal> PtosParticipacion { get; set; }

    public Nullable<decimal> PtosInstruccion { get; set; }

    public Nullable<decimal> PtosOtros { get; set; }

    public string ExplicacionOtros { get; set; }

    public string Observacion { get; set; }

    public Nullable<int> MesCarrera { get; set; }

    public Nullable<int> AnnoCarrera { get; set; }

    public Nullable<System.DateTime> FecRigePago { get; set; }

    public Nullable<decimal> HsExcPar { get; set; }

    public Nullable<decimal> HsExcApr { get; set; }

    public string NumResolucion { get; set; }

    public Nullable<System.DateTime> FecResolucion { get; set; }

    public string Periodo { get; set; }

    public string Grado { get; set; }

    public string Nivel { get; set; }

    public Nullable<decimal> AnnoExpEst { get; set; }

    public Nullable<decimal> AprovechamientoEst { get; set; }

    public Nullable<decimal> ParticipacionEst { get; set; }

    public Nullable<decimal> HoraAprEst { get; set; }

    public Nullable<decimal> HoraParEst { get; set; }

    public Nullable<decimal> PtosGrEst { get; set; }

    public Nullable<decimal> PtosAprEst { get; set; }

    public Nullable<decimal> PtosExpEst { get; set; }

    public Nullable<decimal> PtosParEst { get; set; }

    public Nullable<decimal> PtosOtrEst { get; set; }

    public Nullable<decimal> ExcParEst { get; set; }

    public Nullable<decimal> ExcAprEst { get; set; }

    public Nullable<decimal> CAprovechamiento { get; set; }

    public Nullable<decimal> CParticipacion { get; set; }

    public Nullable<decimal> CInstruccion { get; set; }

    public Nullable<decimal> ExpDoc { get; set; }

    public string Movimiento { get; set; }

    public string Observacion1 { get; set; }

    public string Observacion2 { get; set; }

    public string Observacion3 { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public Nullable<decimal> PtosPublicacion { get; set; }

    public Nullable<decimal> PtosExpDoc { get; set; }

    public Nullable<decimal> PtosOrgInt { get; set; }

    public Nullable<System.DateTime> RigeEst { get; set; }

    public string CalficacionEst { get; set; }

}

}
