
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class C_PeriodosBorrar
{

    public int PK_PeriodoVacaciones { get; set; }

    public string IdCedulaFuncionario { get; set; }

    public string IndPeriodo { get; set; }

    public Nullable<double> IndSaldo { get; set; }

    public Nullable<long> row_num { get; set; }

}

}
