
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class C_RebajoPendientes
{

    public int ID { get; set; }

    public int PK_Funcionario { get; set; }

    public Nullable<System.DateTime> FecIngreso { get; set; }

    public Nullable<int> PROCESADO { get; set; }

}

}
