
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CalificacionNombramientoFuncionarios
{

    public CalificacionNombramientoFuncionarios()
    {

        this.CalificacionCapacitacion = new HashSet<CalificacionCapacitacion>();

        this.CalificacionObservaciones = new HashSet<CalificacionObservaciones>();

        this.DetalleCalificacionSeguimiento = new HashSet<DetalleCalificacionSeguimiento>();

    }


    public int PK_CalificacionNombramiento { get; set; }

    public int FK_PeriodoCalificacion { get; set; }

    public int FK_Nombramiento { get; set; }

    public Nullable<int> FK_Puesto { get; set; }

    public int FK_Funcionario { get; set; }

    public Nullable<System.DateTime> FecRige { get; set; }

    public Nullable<System.DateTime> FecVence { get; set; }

    public Nullable<int> FK_Seccion { get; set; }

    public Nullable<int> FK_Departamento { get; set; }

    public Nullable<int> FK_DireccionGeneral { get; set; }

    public Nullable<int> FK_Division { get; set; }

    public int FK_OcupacionReal { get; set; }

    public Nullable<int> IdJefeInmediato { get; set; }

    public Nullable<int> IdJefeSuperior { get; set; }

    public int NumTipo { get; set; }

    public string ObsNoCalificacion { get; set; }

    public int FK_DetallePuesto { get; set; }

    public decimal PorAutoEvaluacion { get; set; }



    public virtual ICollection<CalificacionCapacitacion> CalificacionCapacitacion { get; set; }

    public virtual PeriodoCalificacion PeriodoCalificacion { get; set; }

    public virtual ICollection<CalificacionObservaciones> CalificacionObservaciones { get; set; }

    public virtual ICollection<DetalleCalificacionSeguimiento> DetalleCalificacionSeguimiento { get; set; }

}

}
