
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CambioPorAccionPersonal
{

    public int PK_CambioPorAccionPersonal { get; set; }

    public int FK_Nombramiento { get; set; }

    public int FK_ComponenteSalarial { get; set; }

    public int FK_AccionPersonal { get; set; }

    public Nullable<decimal> ValorCambio { get; set; }

    public Nullable<int> FK_TipoCambioPorAccionPersonal { get; set; }

    public Nullable<int> Estado { get; set; }



    public virtual AccionPersonal AccionPersonal { get; set; }

    public virtual ComponenteSalarial ComponenteSalarial { get; set; }

    public virtual Nombramiento Nombramiento { get; set; }

    public virtual TipoCambioPorAccionPersonal TipoCambioPorAccionPersonal { get; set; }

}

}
