
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CartasPresentacion
{

    public int PK_CartasPresentacion { get; set; }

    public string NumCarta { get; set; }

    public Nullable<System.DateTime> FecCarta { get; set; }

    public Nullable<System.DateTime> FecRige { get; set; }

    public Nullable<System.DateTime> FecVence { get; set; }

    public int FK_Nombramiento { get; set; }



    public virtual Nombramiento Nombramiento { get; set; }

}

}
