
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CatalogoPregunta
{

    public CatalogoPregunta()
    {

        this.DetalleCalificacionModificada = new HashSet<DetalleCalificacionModificada>();

        this.DetalleCalificacion = new HashSet<DetalleCalificacion>();

    }


    public int PK_CatalogoPregunta { get; set; }

    public string DesPregunta { get; set; }

    public Nullable<int> IndTipoFormulario { get; set; }

    public Nullable<int> IndEstado { get; set; }

    public string DesTituloP { get; set; }



    public virtual ICollection<DetalleCalificacionModificada> DetalleCalificacionModificada { get; set; }

    public virtual ICollection<DetalleCalificacion> DetalleCalificacion { get; set; }

}

}
