
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CatalogoDeduccion
{

    public CatalogoDeduccion()
    {

        this.DeduccionEfectuada = new HashSet<DeduccionEfectuada>();

        this.DetalleDeduccion = new HashSet<DetalleDeduccion>();

    }


    public int PK_CatalogoDeduccion { get; set; }

    public int FK_TipoDeduccion { get; set; }

    public Nullable<int> CodDeduccion { get; set; }

    public string DesDeduccion { get; set; }

    public decimal PorDeduccion { get; set; }



    public virtual TipoDeduccion TipoDeduccion { get; set; }

    public virtual ICollection<DeduccionEfectuada> DeduccionEfectuada { get; set; }

    public virtual ICollection<DetalleDeduccion> DetalleDeduccion { get; set; }

}

}
