
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CatCampo
{

    public int PK_Campo { get; set; }

    public string NomCampo { get; set; }

    public string DesTabla { get; set; }

    public string DesColumna { get; set; }

    public string DesEnPantalla { get; set; }

}

}
