
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CatDiaViaticoGasto
{

    public int PK_CatalogoDia { get; set; }

    public int FK_TipoDia { get; set; }

    public string DesDia { get; set; }

    public System.DateTime FecDia { get; set; }

    public bool IndRebajo { get; set; }

    public bool IndViatico { get; set; }

    public bool IndGasto { get; set; }



    public virtual TipoDia TipoDia { get; set; }

}

}
