
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CompetenciaGrupoOcupacional
{

    public CompetenciaGrupoOcupacional()
    {

        this.ComportamientoGrupoOcupacional = new HashSet<ComportamientoGrupoOcupacional>();

    }


    public int PK_CompetenciaGrupoOcupacional { get; set; }

    public Nullable<int> IndNivel { get; set; }

    public string NomCompetencia { get; set; }

    public Nullable<int> FK_Cargo { get; set; }



    public virtual Cargo Cargo { get; set; }

    public virtual ICollection<ComportamientoGrupoOcupacional> ComportamientoGrupoOcupacional { get; set; }

}

}
