
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CompetenciaTransversalCargo
{

    public CompetenciaTransversalCargo()
    {

        this.ComportamientoTransversal = new HashSet<ComportamientoTransversal>();

    }


    public int PK_CompetenciaTransversalCargo { get; set; }

    public Nullable<int> IndTipoCompetencia { get; set; }

    public Nullable<int> IntNivelDominio { get; set; }

    public Nullable<int> FK_Cargo { get; set; }



    public virtual Cargo Cargo { get; set; }

    public virtual ICollection<ComportamientoTransversal> ComportamientoTransversal { get; set; }

}

}
