
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class CuentaBancaria
{

    public int PK_CuentaBancaria { get; set; }

    public string CtaCliente { get; set; }

    public Nullable<int> FK_EntidadFinanciera { get; set; }

    public Nullable<int> FK_DetalleContratacion { get; set; }

    public Nullable<int> IndEstadoCtaBancaria { get; set; }



    public virtual DetalleContratacion DetalleContratacion { get; set; }

    public virtual EntidadFinanciera EntidadFinanciera { get; set; }

}

}
