
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Departamento
{

    public Departamento()
    {

        this.UbicacionAdministrativa = new HashSet<UbicacionAdministrativa>();

        this.Desarraigo = new HashSet<Desarraigo>();

        this.ListaNombramientosActivos = new HashSet<ListaNombramientosActivos>();

    }


    public int PK_Departamento { get; set; }

    public string NomDepartamento { get; set; }

    public Nullable<int> IndEstadoDepartamento { get; set; }



    public virtual ICollection<UbicacionAdministrativa> UbicacionAdministrativa { get; set; }

    public virtual ICollection<Desarraigo> Desarraigo { get; set; }

    public virtual ICollection<ListaNombramientosActivos> ListaNombramientosActivos { get; set; }

}

}
