
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DesgloseSalarial
{

    public DesgloseSalarial()
    {

        this.DetalleDesgloseSalarial = new HashSet<DetalleDesgloseSalarial>();

        this.DetalleDeduccion = new HashSet<DetalleDeduccion>();

        this.RegistroTiempoExtra = new HashSet<RegistroTiempoExtra>();

        this.RegistroTiempoExtra1 = new HashSet<RegistroTiempoExtra>();

        this.Aguinaldo = new HashSet<Aguinaldo>();

    }


    public int PK_DesgloseSalarial { get; set; }

    public System.DateTime IndPeriodo { get; set; }

    public Nullable<int> FK_Nombramiento { get; set; }

    public Nullable<System.DateTime> FecCarga { get; set; }



    public virtual ICollection<DetalleDesgloseSalarial> DetalleDesgloseSalarial { get; set; }

    public virtual Nombramiento Nombramiento { get; set; }

    public virtual ICollection<DetalleDeduccion> DetalleDeduccion { get; set; }

    public virtual ICollection<RegistroTiempoExtra> RegistroTiempoExtra { get; set; }

    public virtual ICollection<RegistroTiempoExtra> RegistroTiempoExtra1 { get; set; }

    public virtual ICollection<Aguinaldo> Aguinaldo { get; set; }

}

}
