
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DetallePuesto
{

    public DetallePuesto()
    {

        this.DetalleAccionPersonal = new HashSet<DetalleAccionPersonal>();

        this.DetallePuestoRubro = new HashSet<DetallePuestoRubro>();

        this.ListaNombramientosActivos = new HashSet<ListaNombramientosActivos>();

        this.OrdenMovimiento = new HashSet<OrdenMovimiento>();

    }


    public int PK_DetallePuesto { get; set; }

    public Nullable<int> FK_SubEspecialidad { get; set; }

    public Nullable<int> FK_OcupacionReal { get; set; }

    public Nullable<int> FK_Puesto { get; set; }

    public Nullable<int> FK_Especialidad { get; set; }

    public Nullable<int> FK_Clase { get; set; }

    public Nullable<int> FK_TipoPuesto { get; set; }

    public Nullable<int> FK_ContenidoPresupuestario { get; set; }

    public Nullable<int> IndEstadoDetallePuesto { get; set; }

    public Nullable<System.DateTime> FecRige { get; set; }

    public Nullable<int> FK_Escala { get; set; }

    public Nullable<decimal> PorProhibicion { get; set; }

    public Nullable<decimal> PorDedicacion { get; set; }

    public Nullable<int> FK_Nombramiento { get; set; }



    public virtual Clase Clase { get; set; }

    public virtual ContenidoPresupuestario ContenidoPresupuestario { get; set; }

    public virtual ICollection<DetalleAccionPersonal> DetalleAccionPersonal { get; set; }

    public virtual EscalaSalarial EscalaSalarial { get; set; }

    public virtual Especialidad Especialidad { get; set; }

    public virtual OcupacionReal OcupacionReal { get; set; }

    public virtual Puesto Puesto { get; set; }

    public virtual SubEspecialidad SubEspecialidad { get; set; }

    public virtual TipoPuesto TipoPuesto { get; set; }

    public virtual ICollection<DetallePuestoRubro> DetallePuestoRubro { get; set; }

    public virtual ICollection<ListaNombramientosActivos> ListaNombramientosActivos { get; set; }

    public virtual ICollection<OrdenMovimiento> OrdenMovimiento { get; set; }

}

}
