
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleDeduccionGastoTransporte
{

    public int PK_DetalleDeduccionGastoTransporte { get; set; }

    public Nullable<int> FK_MovimientoGastoTransporte { get; set; }

    public string DesMotivo { get; set; }

    public string FecRige { get; set; }

    public string FecVence { get; set; }

    public Nullable<int> NumNoDias { get; set; }

    public string MontMontoBajar { get; set; }

    public string MontMontoRebajarConp { get; set; }

    public string TotRebajar { get; set; }

    public string NumAccionPersonal { get; set; }



    public virtual MovimientoGastoTransporte MovimientoGastoTransporte { get; set; }

}

}
