
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleCalificacionSeguimiento
{

    public int PK_Detalle { get; set; }

    public int FK_CalificacionNombramientoFuncionario { get; set; }

    public int FK_Estado { get; set; }

    public int IdJefatura { get; set; }

    public System.DateTime FecRegistro { get; set; }

    public string DesOportunidadMejora { get; set; }

    public string DesPlanAccion { get; set; }

    public System.DateTime FecCierreAccion { get; set; }

    public string DesEvidencia { get; set; }

    public string DesComentario { get; set; }



    public virtual CalificacionNombramientoFuncionarios CalificacionNombramientoFuncionarios { get; set; }

    public virtual CatMetaEstado CatMetaEstado { get; set; }

    public virtual Funcionario Funcionario { get; set; }

}

}
