
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleIncapacidad
{

    public int PK_Detalle { get; set; }

    public int FK_RegistroIncapacidad { get; set; }

    public System.DateTime FecDia { get; set; }

    public decimal PorSubsidio { get; set; }

    public decimal MtoSubsidio { get; set; }



    public virtual RegistroIncapacidad RegistroIncapacidad { get; set; }

}

}
