
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DetallePuntosAdicional
{

    public int PK_DetallePuntos { get; set; }

    public Nullable<int> CantPtos { get; set; }

    public string Observaciones { get; set; }

    public string NumDoc { get; set; }

    public Nullable<System.DateTime> FecRegistro { get; set; }

    public int FK_FormacionAcademica { get; set; }



    public virtual FormacionAcademica FormacionAcademica { get; set; }

    public virtual FormacionAcademica FormacionAcademica1 { get; set; }

}

}
