
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DetalleAccionPersonalAnterior
{

    public int PK_Detalle { get; set; }

    public int FK_AccionPersonal { get; set; }

    public int CodNombramiento { get; set; }

    public int CodNombramientoAnt { get; set; }

    public int CodDetallePuesto { get; set; }

    public int CodDetallePuestoAnt { get; set; }

    public int CodUbicacionAdminitrativa { get; set; }

    public int CodUbicacionAdminitrativaAnt { get; set; }

    public int NumAnualidad { get; set; }

    public int NumAnualidadAnt { get; set; }

    public int NumAnualidadAcumulada { get; set; }

    public int NumAnualidadAcumuladaAnt { get; set; }

    public int CodComponente { get; set; }

    public decimal MtoComponente { get; set; }

    public decimal MtoComponenteAnt { get; set; }



    public virtual AccionPersonal AccionPersonal { get; set; }

}

}
