
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DetallePrestacionCuadro
{

    public int PK_DetalleCuadro { get; set; }

    public int FK_Prestacion { get; set; }

    public int FK_Tipo { get; set; }

    public System.DateTime FecPeriodo { get; set; }

    public decimal MtoSalario { get; set; }

    public decimal MtoVacaciones { get; set; }

    public decimal MtoExtras { get; set; }

    public decimal MtoFeriados { get; set; }

    public decimal MtoTotal { get; set; }

    public decimal MtoEscolar { get; set; }



    public virtual PrestacionLegal PrestacionLegal { get; set; }

    public virtual TipoPrestacionCuadro TipoPrestacionCuadro { get; set; }

}

}
