
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DetallePrestacion
{

    public int PK_DetallePrestacion { get; set; }

    public int FK_Presupuesto { get; set; }

    public Nullable<int> FK_Division { get; set; }

    public Nullable<int> FK_DireccionGeneral { get; set; }

    public Nullable<int> FK_Departamento { get; set; }

    public Nullable<int> FK_Seccion { get; set; }

    public Nullable<int> FK_PrestacionLegal { get; set; }

    public Nullable<int> FK_AccionIngreso { get; set; }

    public Nullable<int> FK_AccionCese { get; set; }

    public string NomJefe { get; set; }

    public string DesPuestoJefatura { get; set; }

    public int FK_Usuario { get; set; }

    public Nullable<decimal> CntDiasProporcionales { get; set; }

    public Nullable<decimal> CntDiasVacaciones { get; set; }



    public virtual PrestacionLegal PrestacionLegal { get; set; }

}

}
