
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class DiaPagado
{

    public int PK_DiaPagado { get; set; }

    public int FK_PagoFeriado { get; set; }

    public int FK_CatalogoDia { get; set; }

    public int CntHora { get; set; }

    public decimal MtoSalarioHora { get; set; }

    public decimal MtoTotal { get; set; }

    public string AnioPago { get; set; }



    public virtual CatalogoDia CatalogoDia { get; set; }

    public virtual PagoFeriado PagoFeriado { get; set; }

}

}
