
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Direccion
{

    public int PK_Direccion { get; set; }

    public int FK_Distrito { get; set; }

    public int FK_Funcionario { get; set; }

    public string DirExacta { get; set; }

    public Nullable<int> IndEstadoDireccion { get; set; }



    public virtual Distrito Distrito { get; set; }

    public virtual Funcionario Funcionario { get; set; }

}

}
