
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Distrito
{

    public Distrito()
    {

        this.Desarraigo = new HashSet<Desarraigo>();

        this.Desarraigo1 = new HashSet<Desarraigo>();

        this.Desarraigo2 = new HashSet<Desarraigo>();

        this.Direccion = new HashSet<Direccion>();

        this.UbicacionPuesto = new HashSet<UbicacionPuesto>();

        this.GastoTransporte = new HashSet<GastoTransporte>();

        this.GastoTransporte1 = new HashSet<GastoTransporte>();

        this.ViaticoCorrido = new HashSet<ViaticoCorrido>();

    }


    public int PK_Distrito { get; set; }

    public int FK_Canton { get; set; }

    public string NomDistrito { get; set; }

    public string CodPostalDistrito { get; set; }



    public virtual Canton Canton { get; set; }

    public virtual ICollection<Desarraigo> Desarraigo { get; set; }

    public virtual ICollection<Desarraigo> Desarraigo1 { get; set; }

    public virtual ICollection<Desarraigo> Desarraigo2 { get; set; }

    public virtual ICollection<Direccion> Direccion { get; set; }

    public virtual ICollection<UbicacionPuesto> UbicacionPuesto { get; set; }

    public virtual ICollection<GastoTransporte> GastoTransporte { get; set; }

    public virtual ICollection<GastoTransporte> GastoTransporte1 { get; set; }

    public virtual ICollection<ViaticoCorrido> ViaticoCorrido { get; set; }

}

}
