
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Division
{

    public Division()
    {

        this.UbicacionAdministrativa = new HashSet<UbicacionAdministrativa>();

        this.ListaNombramientosActivos = new HashSet<ListaNombramientosActivos>();

    }


    public int PK_Division { get; set; }

    public string NomDivision { get; set; }



    public virtual ICollection<UbicacionAdministrativa> UbicacionAdministrativa { get; set; }

    public virtual ICollection<ListaNombramientosActivos> ListaNombramientosActivos { get; set; }

}

}
