
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class EntidadEducativa
{

    public EntidadEducativa()
    {

        this.CursoCapacitacion = new HashSet<CursoCapacitacion>();

        this.CursoGrado = new HashSet<CursoGrado>();

    }


    public int PK_EntidadEducativa { get; set; }

    public string NomEntidad { get; set; }

    public Nullable<int> TipEntidad { get; set; }

    public Nullable<int> Estado { get; set; }



    public virtual ICollection<CursoCapacitacion> CursoCapacitacion { get; set; }

    public virtual ICollection<CursoGrado> CursoGrado { get; set; }

}

}
