
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class EstadoGastoTransporte
{

    public EstadoGastoTransporte()
    {

        this.GastoTransporte = new HashSet<GastoTransporte>();

        this.GastoTransporteRutas = new HashSet<GastoTransporteRutas>();

    }


    public int PK_EstadoGastosTransporte { get; set; }

    public string NomEstado { get; set; }



    public virtual ICollection<GastoTransporte> GastoTransporte { get; set; }

    public virtual ICollection<GastoTransporteRutas> GastoTransporteRutas { get; set; }

}

}
