
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class EstadoPuesto
{

    public EstadoPuesto()
    {

        this.Puesto = new HashSet<Puesto>();

    }


    public int PK_EstadoPuesto { get; set; }

    public string DesEstadoPuesto { get; set; }



    public virtual ICollection<Puesto> Puesto { get; set; }

}

}
