
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class EstudioPuesto
{

    public int PK_EstudioPuesto { get; set; }

    public string NumOficio { get; set; }

    public string NumResolucion { get; set; }

    public Nullable<System.DateTime> FecResolucion { get; set; }

    public Nullable<int> FK_Puesto { get; set; }

    public string ObsEstudioPuesto { get; set; }



    public virtual Puesto Puesto { get; set; }

}

}
