
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class EvidenciaComportamientoTransversal
{

    public int PK_EvidenciaComportamientoTransversal { get; set; }

    public string DesEvidencia { get; set; }

    public Nullable<int> FK_ComportamientoTransversal { get; set; }



    public virtual ComportamientoTransversal ComportamientoTransversal { get; set; }

}

}
