
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class ExpedienteFuncionario
{

    public ExpedienteFuncionario()
    {

        this.BoletaPrestamo = new HashSet<BoletaPrestamo>();

        this.Tomo = new HashSet<Tomo>();

    }


    public int PK_IdExpedienteFuncionario { get; set; }

    public int FK_Funcionario { get; set; }

    public Nullable<System.DateTime> FecCreacion { get; set; }

    public int Estado { get; set; }

    public Nullable<System.DateTime> FecTrasladoArchivoCentral { get; set; }

    public int numExpediente { get; set; }

    public string numExpedienteEnArchivo { get; set; }

    public string numCaja { get; set; }



    public virtual ICollection<BoletaPrestamo> BoletaPrestamo { get; set; }

    public virtual Funcionario Funcionario { get; set; }

    public virtual ICollection<Tomo> Tomo { get; set; }

}

}
