
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Folio
{

    public int PK_IdFolio { get; set; }

    public Nullable<int> FK_IdTomo { get; set; }

    public string Descripcion { get; set; }

    public Nullable<System.DateTime> FecCreacion { get; set; }

    public int NumFolio { get; set; }



    public virtual Tomo Tomo { get; set; }

}

}
