
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Funcionario
{

    public Funcionario()
    {

        this.ActividadFuncionario = new HashSet<ActividadFuncionario>();

        this.BitacoraIncidencia = new HashSet<BitacoraIncidencia>();

        this.CalificacionEncargado = new HashSet<CalificacionEncargado>();

        this.CatPermisoEvidencia = new HashSet<CatPermisoEvidencia>();

        this.DetalleAcceso = new HashSet<DetalleAcceso>();

        this.DetalleCalificacionSeguimiento = new HashSet<DetalleCalificacionSeguimiento>();

        this.DetalleContratacion = new HashSet<DetalleContratacion>();

        this.Direccion = new HashSet<Direccion>();

        this.EjecutorActividad = new HashSet<EjecutorActividad>();

        this.ExpedienteFuncionario = new HashSet<ExpedienteFuncionario>();

        this.FormacionAcademica = new HashSet<FormacionAcademica>();

        this.HistorialEstadoCivil = new HashSet<HistorialEstadoCivil>();

        this.InformacionContacto = new HashSet<InformacionContacto>();

        this.PagoExtraordinario = new HashSet<PagoExtraordinario>();

        this.Incidencia = new HashSet<Incidencia>();

        this.Incidencia1 = new HashSet<Incidencia>();

        this.ListaNombramientosActivos = new HashSet<ListaNombramientosActivos>();

        this.MetaIndividualCalificacion = new HashSet<MetaIndividualCalificacion>();

        this.MetaObjetivoInstitucional = new HashSet<MetaObjetivoInstitucional>();

        this.Nombramiento = new HashSet<Nombramiento>();

        this.OrdenMovimiento = new HashSet<OrdenMovimiento>();

        this.Aguinaldo = new HashSet<Aguinaldo>();

    }


    public int PK_Funcionario { get; set; }

    public int FK_EstadoFuncionario { get; set; }

    public string IdCedulaFuncionario { get; set; }

    public string NomFuncionario { get; set; }

    public string NomPrimerApellido { get; set; }

    public string NomSegundoApellido { get; set; }

    public Nullable<System.DateTime> FecNacimiento { get; set; }

    public string IndSexo { get; set; }



    public virtual ICollection<ActividadFuncionario> ActividadFuncionario { get; set; }

    public virtual ICollection<BitacoraIncidencia> BitacoraIncidencia { get; set; }

    public virtual ICollection<CalificacionEncargado> CalificacionEncargado { get; set; }

    public virtual ICollection<CatPermisoEvidencia> CatPermisoEvidencia { get; set; }

    public virtual ICollection<DetalleAcceso> DetalleAcceso { get; set; }

    public virtual ICollection<DetalleCalificacionSeguimiento> DetalleCalificacionSeguimiento { get; set; }

    public virtual ICollection<DetalleContratacion> DetalleContratacion { get; set; }

    public virtual ICollection<Direccion> Direccion { get; set; }

    public virtual ICollection<EjecutorActividad> EjecutorActividad { get; set; }

    public virtual EstadoFuncionario EstadoFuncionario { get; set; }

    public virtual ICollection<ExpedienteFuncionario> ExpedienteFuncionario { get; set; }

    public virtual ICollection<FormacionAcademica> FormacionAcademica { get; set; }

    public virtual ICollection<HistorialEstadoCivil> HistorialEstadoCivil { get; set; }

    public virtual ICollection<InformacionContacto> InformacionContacto { get; set; }

    public virtual ICollection<PagoExtraordinario> PagoExtraordinario { get; set; }

    public virtual ICollection<Incidencia> Incidencia { get; set; }

    public virtual ICollection<Incidencia> Incidencia1 { get; set; }

    public virtual ICollection<ListaNombramientosActivos> ListaNombramientosActivos { get; set; }

    public virtual ICollection<MetaIndividualCalificacion> MetaIndividualCalificacion { get; set; }

    public virtual ICollection<MetaObjetivoInstitucional> MetaObjetivoInstitucional { get; set; }

    public virtual ICollection<Nombramiento> Nombramiento { get; set; }

    public virtual ICollection<OrdenMovimiento> OrdenMovimiento { get; set; }

    public virtual ICollection<Aguinaldo> Aguinaldo { get; set; }

}

}
