
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class GastoTransporte
{

    public GastoTransporte()
    {

        this.DetalleAsignacionGastoTransporteModificada = new HashSet<DetalleAsignacionGastoTransporteModificada>();

        this.GastoTransporteReintegroDias = new HashSet<GastoTransporteReintegroDias>();

        this.GastoTransporteRutas = new HashSet<GastoTransporteRutas>();

        this.MovimientoGastoTransporte = new HashSet<MovimientoGastoTransporte>();

        this.PagoGastoTransporte = new HashSet<PagoGastoTransporte>();

    }


    public int PK_GastosTransporte { get; set; }

    public Nullable<int> FK_Nombramiento { get; set; }

    public Nullable<int> FK_EstadoGastosTransporte { get; set; }

    public decimal MonOriginal { get; set; }

    public decimal MonActual { get; set; }

    public string ObsGastosTransporte { get; set; }

    public Nullable<System.DateTime> FecInicGastosTransporte { get; set; }

    public Nullable<System.DateTime> FecFinGastosTransporte { get; set; }

    public string HojaIndividualizada { get; set; }

    public Nullable<int> FK_Presupuesto { get; set; }

    public System.DateTime FecRegistro { get; set; }

    public Nullable<System.DateTime> FecContrato { get; set; }

    public string NumDocumento { get; set; }

    public byte[] ImgDocumento { get; set; }

    public Nullable<int> FK_DistritoContrato { get; set; }

    public Nullable<int> FK_DistritoTrabajo { get; set; }



    public virtual ICollection<DetalleAsignacionGastoTransporteModificada> DetalleAsignacionGastoTransporteModificada { get; set; }

    public virtual Distrito Distrito { get; set; }

    public virtual Distrito Distrito1 { get; set; }

    public virtual EstadoGastoTransporte EstadoGastoTransporte { get; set; }

    public virtual Nombramiento Nombramiento { get; set; }

    public virtual Presupuesto Presupuesto { get; set; }

    public virtual ICollection<GastoTransporteReintegroDias> GastoTransporteReintegroDias { get; set; }

    public virtual ICollection<GastoTransporteRutas> GastoTransporteRutas { get; set; }

    public virtual ICollection<MovimientoGastoTransporte> MovimientoGastoTransporte { get; set; }

    public virtual ICollection<PagoGastoTransporte> PagoGastoTransporte { get; set; }

}

}
