
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class GastoTransporteReintegroDias
{

    public int PK_Reintegro { get; set; }

    public int FK_GastoTransporte { get; set; }

    public System.DateTime FecDia { get; set; }

    public decimal MonReintegro { get; set; }

    public string ObsMotivo { get; set; }

    public int IndEstado { get; set; }



    public virtual GastoTransporte GastoTransporte { get; set; }

}

}
