
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class HistorialEstadoCivil
{

    public int PK_HistorialEstadoCivil { get; set; }

    public int FK_CatEstadoCivil { get; set; }

    public int FK_Funcionario { get; set; }

    public System.DateTime FecInicio { get; set; }

    public Nullable<System.DateTime> FecFin { get; set; }



    public virtual CatEstadoCivil CatEstadoCivil { get; set; }

    public virtual Funcionario Funcionario { get; set; }

}

}
