
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class ListaNombramientosActivos
{

    public int PK_Nombramiento { get; set; }

    public int PK_Puesto { get; set; }

    public int PK_Funcionario { get; set; }

    public Nullable<int> PK_Seccion { get; set; }

    public Nullable<int> PK_Departamento { get; set; }

    public Nullable<int> PK_Direccion { get; set; }

    public Nullable<int> PK_Division { get; set; }

    public int PK_DetallePuesto { get; set; }

    public int IndPropiedad { get; set; }



    public virtual Departamento Departamento { get; set; }

    public virtual DetallePuesto DetallePuesto { get; set; }

    public virtual DireccionGeneral DireccionGeneral { get; set; }

    public virtual Division Division { get; set; }

    public virtual Funcionario Funcionario { get; set; }

    public virtual Nombramiento Nombramiento { get; set; }

    public virtual Puesto Puesto { get; set; }

    public virtual Seccion Seccion { get; set; }

}

}
