
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class MetaObjetivoCalificacion
{

    public MetaObjetivoCalificacion()
    {

        this.MetaIndividualCalificacion = new HashSet<MetaIndividualCalificacion>();

    }


    public int PK_Meta { get; set; }

    public int FK_ObjetivoCalificacion { get; set; }

    public string DesMeta { get; set; }

    public Nullable<System.DateTime> FecInicio { get; set; }

    public Nullable<System.DateTime> FecFinalizacion { get; set; }

    public int TipMeta { get; set; }

    public int IndEstado { get; set; }

    public string DesProductoEspecifico { get; set; }

    public string DesFuenteDatos { get; set; }

    public string DesSupuestos { get; set; }

    public string DesNotasTecnicas { get; set; }

    public string DesTipoIndicador { get; set; }

    public string DesIndicador { get; set; }

    public string DesDimension { get; set; }

    public string DesMetaAnual { get; set; }



    public virtual ICollection<MetaIndividualCalificacion> MetaIndividualCalificacion { get; set; }

    public virtual ObjetivoCalificacion ObjetivoCalificacion { get; set; }

}

}
