
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class MetaObjetivoInstitucional
{

    public MetaObjetivoInstitucional()
    {

        this.ActividadMeta = new HashSet<ActividadMeta>();

    }


    public int PK_Metas { get; set; }

    public Nullable<int> FK_UbicacionAdministrativa { get; set; }

    public Nullable<int> FK_ObjetivoInstitucional { get; set; }

    public Nullable<int> FK_Funcionario { get; set; }

    public Nullable<int> IndEstado { get; set; }

    public string DesObservaciones { get; set; }

    public Nullable<System.DateTime> FecInicio { get; set; }

    public Nullable<System.DateTime> FecFinalizacion { get; set; }

    public Nullable<int> TipMeta { get; set; }



    public virtual ICollection<ActividadMeta> ActividadMeta { get; set; }

    public virtual Funcionario Funcionario { get; set; }

    public virtual ObjetivoInstitucional ObjetivoInstitucional { get; set; }

    public virtual UbicacionAdministrativa UbicacionAdministrativa { get; set; }

}

}
