
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class MetaIndividualEvidencia
{

    public int PK_Evidencia { get; set; }

    public int FK_Meta { get; set; }

    public string DesEvidencia { get; set; }

    public int IndEstado { get; set; }

    public System.DateTime FecRegistro { get; set; }

    public string DesEnlace { get; set; }

    public byte[] DocAdjunto { get; set; }

    public string DesObservaciones { get; set; }

    public string DesArchivo { get; set; }



    public virtual MetaIndividualCalificacion MetaIndividualCalificacion { get; set; }

}

}
