
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class MetaIndividualCalificacion
{

    public MetaIndividualCalificacion()
    {

        this.MetaIndividualEvidencia = new HashSet<MetaIndividualEvidencia>();

        this.MetaIndividualInforme = new HashSet<MetaIndividualInforme>();

    }


    public int PK_Meta { get; set; }

    public int FK_PeriodoCalificacion { get; set; }

    public int FK_Funcionario { get; set; }

    public int FK_Prioridad { get; set; }

    public int FK_Estado { get; set; }

    public Nullable<int> FK_MetaObjetivo { get; set; }

    public string DesMeta { get; set; }

    public System.DateTime FecDesde { get; set; }

    public System.DateTime FecHasta { get; set; }

    public Nullable<System.DateTime> FecFinalizado { get; set; }

    public System.DateTime FecRegistro { get; set; }

    public string DesIndicadorMensual { get; set; }

    public int FK_TipoIndicador { get; set; }

    public decimal NumIndicador { get; set; }

    public string DesResultadoProduccion { get; set; }

    public int IndEsTeletrabajable { get; set; }

    public string DesObservaciones { get; set; }

    public int IdJefeInmediato { get; set; }

    public decimal PorPeso { get; set; }

    public int IndModificar { get; set; }



    public virtual CatMetaEstado CatMetaEstado { get; set; }

    public virtual CatMetaPrioridad CatMetaPrioridad { get; set; }

    public virtual Funcionario Funcionario { get; set; }

    public virtual MetaIndividualCalificacion MetaIndividualCalificacion1 { get; set; }

    public virtual MetaIndividualCalificacion MetaIndividualCalificacion2 { get; set; }

    public virtual MetaObjetivoCalificacion MetaObjetivoCalificacion { get; set; }

    public virtual PeriodoCalificacion PeriodoCalificacion { get; set; }

    public virtual TipoIndicadorMeta TipoIndicadorMeta { get; set; }

    public virtual ICollection<MetaIndividualEvidencia> MetaIndividualEvidencia { get; set; }

    public virtual ICollection<MetaIndividualInforme> MetaIndividualInforme { get; set; }

}

}
