
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Modalidad
{

    public Modalidad()
    {

        this.CursoCapacitacion = new HashSet<CursoCapacitacion>();

    }


    public int PK_Modalidad { get; set; }

    public string DesModalidad { get; set; }

    public Nullable<int> IndTopePuntos { get; set; }



    public virtual ICollection<CursoCapacitacion> CursoCapacitacion { get; set; }

}

}
