
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class MontoCaucion
{

    public MontoCaucion()
    {

        this.Caucion = new HashSet<Caucion>();

    }


    public int PK_MontoCaucion { get; set; }

    public string IndNivel { get; set; }

    public Nullable<decimal> MtoColones { get; set; }

    public string DesMontoCaucion { get; set; }

    public Nullable<System.DateTime> FecRige { get; set; }

    public string DesJustificacion { get; set; }

    public Nullable<int> IndEstadoMonto { get; set; }

    public string DesJustificacionInactivo { get; set; }

    public Nullable<System.DateTime> FecVencimiento { get; set; }



    public virtual ICollection<Caucion> Caucion { get; set; }

}

}
