
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class ObjetivoInstitucional
{

    public ObjetivoInstitucional()
    {

        this.MetaObjetivoInstitucional = new HashSet<MetaObjetivoInstitucional>();

    }


    public int PK_ObjetivoInstitucional { get; set; }

    public string DesObjetivo { get; set; }

    public int FK_PeriodoCalificacion { get; set; }



    public virtual ICollection<MetaObjetivoInstitucional> MetaObjetivoInstitucional { get; set; }

    public virtual PeriodoCalificacion PeriodoCalificacion { get; set; }

}

}
