
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class ObjetivoCalificacion
{

    public ObjetivoCalificacion()
    {

        this.MetaObjetivoCalificacion = new HashSet<MetaObjetivoCalificacion>();

    }


    public int PK_ObjetivoCalificacion { get; set; }

    public string DesObjetivo { get; set; }

    public int FK_PeriodoCalificacion { get; set; }

    public int FK_Seccion { get; set; }

    public string DesActividadPresupuestaria { get; set; }

    public string DesProductoPrograma { get; set; }

    public int IndEstado { get; set; }



    public virtual ICollection<MetaObjetivoCalificacion> MetaObjetivoCalificacion { get; set; }

    public virtual PeriodoCalificacion PeriodoCalificacion { get; set; }

    public virtual Seccion Seccion { get; set; }

}

}
