
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class PagoViaticoRetroactivo
{

    public PagoViaticoRetroactivo()
    {

        this.DetallePagoViaticoRetroactivo = new HashSet<DetallePagoViaticoRetroactivo>();

    }


    public int PK_PagoViaticoRetroactivo { get; set; }

    public int FK_PagoViaticoCorrido { get; set; }

    public System.DateTime FecPago { get; set; }

    public decimal MonPago { get; set; }



    public virtual ICollection<DetallePagoViaticoRetroactivo> DetallePagoViaticoRetroactivo { get; set; }

    public virtual PagoViaticoCorrido PagoViaticoCorrido { get; set; }

}

}
