
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class PagoViaticoCorrido
{

    public PagoViaticoCorrido()
    {

        this.DetallePagoViaticoCorrido = new HashSet<DetallePagoViaticoCorrido>();

        this.PagoViaticoRetroactivo = new HashSet<PagoViaticoRetroactivo>();

    }


    public int PK_PagoViaticoCorrido { get; set; }

    public int FK_ViaticoCorrido { get; set; }

    public short IndEstado { get; set; }

    public System.DateTime FecPago { get; set; }

    public decimal MonPago { get; set; }

    public string HojaIndividualizada { get; set; }

    public string NumBoleta { get; set; }

    public string ReservaRecurso { get; set; }

    public System.DateTime FecRegistro { get; set; }



    public virtual ICollection<DetallePagoViaticoCorrido> DetallePagoViaticoCorrido { get; set; }

    public virtual ViaticoCorrido ViaticoCorrido { get; set; }

    public virtual ICollection<PagoViaticoRetroactivo> PagoViaticoRetroactivo { get; set; }

}

}
