
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class PagoPrestacion
{

    public int PK_PagoPrestacion { get; set; }

    public Nullable<decimal> MtoTotal { get; set; }

    public Nullable<decimal> MtoCesantia { get; set; }

    public Nullable<decimal> MtoVacaciones { get; set; }

    public Nullable<decimal> MtoQuincenal { get; set; }

    public Nullable<decimal> MtoDiario { get; set; }

    public Nullable<decimal> MtoEscolar { get; set; }

    public Nullable<decimal> MtoExtras { get; set; }

    public Nullable<System.DateTime> FecPago { get; set; }

    public Nullable<int> IndEstado { get; set; }

}

}
