
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class PagoGastoTransporte
{

    public PagoGastoTransporte()
    {

        this.DetallePagoGastoTransporte = new HashSet<DetallePagoGastoTransporte>();

    }


    public int PK_PagoGastoTransporte { get; set; }

    public int FK_GastosTransporte { get; set; }

    public short IndEstado { get; set; }

    public System.DateTime FecPago { get; set; }

    public decimal MonPago { get; set; }

    public string HojaIndividualizada { get; set; }

    public string NumBoleta { get; set; }

    public string ReservaRecurso { get; set; }

    public System.DateTime FecRegistro { get; set; }

    public decimal MonContrato { get; set; }



    public virtual ICollection<DetallePagoGastoTransporte> DetallePagoGastoTransporte { get; set; }

    public virtual GastoTransporte GastoTransporte { get; set; }

}

}
