
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class PedimentoPuesto
{

    public PedimentoPuesto()
    {

        this.DetalleCambioPedimento = new HashSet<DetalleCambioPedimento>();

        this.OrdenMovimiento = new HashSet<OrdenMovimiento>();

        this.ResolucionPedimento = new HashSet<ResolucionPedimento>();

    }


    public int PK_PedimentoPuesto { get; set; }

    public string NumPedimento { get; set; }

    public int FK_Puesto { get; set; }

    public int FK_Motivo { get; set; }

    public Nullable<System.DateTime> FecPedimento { get; set; }

    public Nullable<bool> IndResolucionPermanente { get; set; }

    public string ObsPedimento { get; set; }



    public virtual ICollection<DetalleCambioPedimento> DetalleCambioPedimento { get; set; }

    public virtual MotivoPedimento MotivoPedimento { get; set; }

    public virtual ICollection<OrdenMovimiento> OrdenMovimiento { get; set; }

    public virtual Puesto Puesto { get; set; }

    public virtual ICollection<ResolucionPedimento> ResolucionPedimento { get; set; }

}

}
