
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class PeriodoEscalaSalarial
{

    public PeriodoEscalaSalarial()
    {

        this.EscalaSalarial = new HashSet<EscalaSalarial>();

    }


    public int PK_Periodo { get; set; }

    public Nullable<System.DateTime> FecInicial { get; set; }

    public Nullable<System.DateTime> FecCierre { get; set; }

    public string NumResolucion { get; set; }

    public Nullable<decimal> MtoPuntoCarrera { get; set; }



    public virtual ICollection<EscalaSalarial> EscalaSalarial { get; set; }

}

}
