
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Programa
{

    public Programa()
    {

        this.ComponentePresupuestario = new HashSet<ComponentePresupuestario>();

        this.DetalleBorradorAccionPersonal = new HashSet<DetalleBorradorAccionPersonal>();

        this.Presupuesto = new HashSet<Presupuesto>();

    }


    public int PK_Programa { get; set; }

    public string DesPrograma { get; set; }

    public Nullable<int> IndEstadoPrograma { get; set; }



    public virtual ICollection<ComponentePresupuestario> ComponentePresupuestario { get; set; }

    public virtual ICollection<DetalleBorradorAccionPersonal> DetalleBorradorAccionPersonal { get; set; }

    public virtual ICollection<Presupuesto> Presupuesto { get; set; }

}

}
