
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Puesto
{

    public Puesto()
    {

        this.CaracteristicasPuesto = new HashSet<CaracteristicasPuesto>();

        this.DetallePuesto = new HashSet<DetallePuesto>();

        this.EstudioPuesto = new HashSet<EstudioPuesto>();

        this.MovimientoPuesto = new HashSet<MovimientoPuesto>();

        this.Nombramiento = new HashSet<Nombramiento>();

        this.PedimentoPuesto = new HashSet<PedimentoPuesto>();

        this.PrestamoPuesto = new HashSet<PrestamoPuesto>();

        this.ListaNombramientosActivos = new HashSet<ListaNombramientosActivos>();

        this.RelPuestoUbicacion = new HashSet<RelPuestoUbicacion>();

        this.TareasPuesto = new HashSet<TareasPuesto>();

    }


    public int PK_Puesto { get; set; }

    public int FK_UbicacionAdministrativa { get; set; }

    public int FK_EstadoPuesto { get; set; }

    public string CodPuesto { get; set; }

    public Nullable<bool> IndPuestoConfianza { get; set; }

    public string ObsPuesto { get; set; }

    public Nullable<int> IndNivelOcupacional { get; set; }

    public int FK_FamiliaPuesto { get; set; }



    public virtual ICollection<CaracteristicasPuesto> CaracteristicasPuesto { get; set; }

    public virtual ICollection<DetallePuesto> DetallePuesto { get; set; }

    public virtual EstadoPuesto EstadoPuesto { get; set; }

    public virtual ICollection<EstudioPuesto> EstudioPuesto { get; set; }

    public virtual FamiliaPuestos FamiliaPuestos { get; set; }

    public virtual ICollection<MovimientoPuesto> MovimientoPuesto { get; set; }

    public virtual ICollection<Nombramiento> Nombramiento { get; set; }

    public virtual ICollection<PedimentoPuesto> PedimentoPuesto { get; set; }

    public virtual ICollection<PrestamoPuesto> PrestamoPuesto { get; set; }

    public virtual ICollection<ListaNombramientosActivos> ListaNombramientosActivos { get; set; }

    public virtual UbicacionAdministrativa UbicacionAdministrativa { get; set; }

    public virtual ICollection<RelPuestoUbicacion> RelPuestoUbicacion { get; set; }

    public virtual ICollection<TareasPuesto> TareasPuesto { get; set; }

}

}
