
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class RegistroPrestacionReal
{

    public int PK_RegistroPagoReal { get; set; }

    public Nullable<decimal> MtoTotalReal { get; set; }

    public Nullable<decimal> MtoVacaciones { get; set; }

    public Nullable<decimal> MtoCesantiaReal { get; set; }

    public Nullable<decimal> MtoQuincenalReal { get; set; }

    public Nullable<decimal> MtoEscolarReal { get; set; }

    public Nullable<decimal> MtoExtrasReal { get; set; }

    public string ObsRegistroPagoReal { get; set; }

}

}
