
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class RegistroVacaciones
{

    public RegistroVacaciones()
    {

        this.ReintegroVacaciones = new HashSet<ReintegroVacaciones>();

    }


    public int PK_RegistroVacaciones { get; set; }

    public Nullable<System.DateTime> FecInicio { get; set; }

    public Nullable<System.DateTime> FecFin { get; set; }

    public Nullable<int> IndEstado { get; set; }

    public Nullable<int> FK_PeriodoVacaciones { get; set; }

    public Nullable<int> IndTipoTransaccion { get; set; }

    public Nullable<decimal> CntDias { get; set; }

    public string NumTransaccion { get; set; }

    public Nullable<System.DateTime> FecActualizacion { get; set; }



    public virtual PeriodoVacaciones PeriodoVacaciones { get; set; }

    public virtual ICollection<ReintegroVacaciones> ReintegroVacaciones { get; set; }

}

}
