
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class RequerimientoEspecificoCargo
{

    public int PK_RequerimientoEspecificoCargo { get; set; }

    public string DesRequisitosEspecificos { get; set; }

    public string DesConocimientos { get; set; }

    public Nullable<int> FK_Cargo { get; set; }



    public virtual Cargo Cargo { get; set; }

}

}
