
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class TipoDia
{

    public TipoDia()
    {

        this.CatalogoDia = new HashSet<CatalogoDia>();

        this.CatDiaViaticoGasto = new HashSet<CatDiaViaticoGasto>();

    }


    public int PK_TipoDia { get; set; }

    public string DesTipoDia { get; set; }



    public virtual ICollection<CatalogoDia> CatalogoDia { get; set; }

    public virtual ICollection<CatDiaViaticoGasto> CatDiaViaticoGasto { get; set; }

}

}
