
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class TipoResolucionPedimento
{

    public TipoResolucionPedimento()
    {

        this.ResolucionPedimento = new HashSet<ResolucionPedimento>();

    }


    public int PK_TipoResolucionPedimento { get; set; }

    public string DesTipoResolucionPedimento { get; set; }



    public virtual ICollection<ResolucionPedimento> ResolucionPedimento { get; set; }

}

}
