
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class TipoJornada
{

    public TipoJornada()
    {

        this.DetalleContratacion = new HashSet<DetalleContratacion>();

    }


    public int PK_TipoJornada { get; set; }

    public string DesTipoJornada { get; set; }

    public string IndInicio { get; set; }

    public string IndFin { get; set; }

    public Nullable<bool> IndAcumulativa { get; set; }

    public string IndDiaLibre { get; set; }

    public Nullable<int> FK_EstadoTipoJornada { get; set; }



    public virtual ICollection<DetalleContratacion> DetalleContratacion { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada1 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada2 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada3 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada4 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada5 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada6 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada7 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada8 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada9 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada10 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada11 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada12 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada13 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada14 { get; set; }

    public virtual EstadoTipoJornada EstadoTipoJornada15 { get; set; }

}

}
