
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class Tomo
{

    public Tomo()
    {

        this.Folio = new HashSet<Folio>();

    }


    public int PK_IdTomo { get; set; }

    public int FK_ExpedienteFuncionario { get; set; }

    public string Descripcion { get; set; }

    public Nullable<System.DateTime> FecCreacion { get; set; }

    public int NumTomo { get; set; }



    public virtual ExpedienteFuncionario ExpedienteFuncionario { get; set; }

    public virtual ICollection<Folio> Folio { get; set; }

}

}
