
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class UbicacionPuesto
{

    public UbicacionPuesto()
    {

        this.RelPuestoUbicacion = new HashSet<RelPuestoUbicacion>();

    }


    public int PK_UbicacionPuesto { get; set; }

    public int FK_TipoUbicacion { get; set; }

    public int FK_Distrito { get; set; }

    public string ObsUbicacionPuesto { get; set; }

    public Nullable<int> IndEstadoUbicacionPuesto { get; set; }

    public Nullable<System.DateTime> FecCambioUbicacion { get; set; }



    public virtual Distrito Distrito { get; set; }

    public virtual ICollection<RelPuestoUbicacion> RelPuestoUbicacion { get; set; }

    public virtual TipoUbicacion TipoUbicacion { get; set; }

}

}
