
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIRH.Datos
{

using System;
    using System.Collections.Generic;
    
public partial class UbicacionAsueto
{

    public int PK_UbicacionAsueto { get; set; }

    public int FK_CatalogoDia { get; set; }

    public int FK_Canton { get; set; }



    public virtual Canton Canton { get; set; }

    public virtual CatalogoDia CatalogoDia { get; set; }

}

}
