//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRH.Web.BorradorAccionPersonalLocal {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BorradorAccionPersonalLocal.ICBorradorAccionPersonalService")]
    public interface ICBorradorAccionPersonalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/GuardarSolicitud", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/GuardarSolicitudResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoBorradorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalHistoricoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAsignacionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBitacoraUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBorradorAccionPersonalDTO))]
        SIRH.DTO.CBaseDTO GuardarSolicitud(SIRH.DTO.CBorradorAccionPersonalDTO registro, string codUsuarioEnvia, string codUsuarioRecibe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/GuardarSolicitud", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/GuardarSolicitudResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> GuardarSolicitudAsync(SIRH.DTO.CBorradorAccionPersonalDTO registro, string codUsuarioEnvia, string codUsuarioRecibe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/GuardarBorrador", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/GuardarBorradorResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoBorradorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalHistoricoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAsignacionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBitacoraUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBorradorAccionPersonalDTO))]
        SIRH.DTO.CBaseDTO GuardarBorrador(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CEstadoBorradorDTO estado, SIRH.DTO.CTipoAccionPersonalDTO tipo, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, string codUsuarioEnvia, string codUsuarioRecibe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/GuardarBorrador", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/GuardarBorradorResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> GuardarBorradorAsync(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CEstadoBorradorDTO estado, SIRH.DTO.CTipoAccionPersonalDTO tipo, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, string codUsuarioEnvia, string codUsuarioRecibe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/EditarBorrador", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/EditarBorradorResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoBorradorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalHistoricoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAsignacionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBitacoraUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBorradorAccionPersonalDTO))]
        SIRH.DTO.CBaseDTO EditarBorrador(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CEstadoBorradorDTO estado, SIRH.DTO.CTipoAccionPersonalDTO tipo, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, SIRH.DTO.CMovimientoBorradorAccionPersonalDTO movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/EditarBorrador", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/EditarBorradorResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> EditarBorradorAsync(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CEstadoBorradorDTO estado, SIRH.DTO.CTipoAccionPersonalDTO tipo, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, SIRH.DTO.CMovimientoBorradorAccionPersonalDTO movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/ObtenerBorrador", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/ObtenerBorradorResponse")]
        SIRH.DTO.CBaseDTO[] ObtenerBorrador(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/ObtenerBorrador", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/ObtenerBorradorResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ObtenerBorradorAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/BuscarSolicitud", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/BuscarSolicitudResponse")]
        SIRH.DTO.CBaseDTO[][] BuscarSolicitud(SIRH.DTO.CBorradorAccionPersonalDTO registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/BuscarSolicitud", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/BuscarSolicitudResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarSolicitudAsync(SIRH.DTO.CBorradorAccionPersonalDTO registro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/BuscarBorrador", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/BuscarBorradorResponse")]
        SIRH.DTO.CBaseDTO[][] BuscarBorrador(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, System.DateTime[] fechasRige, System.DateTime[] fechasVence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/BuscarBorrador", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/BuscarBorradorResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarBorradorAsync(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, System.DateTime[] fechasRige, System.DateTime[] fechasVence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/ActualizarEstado", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/ActualizarEstadoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCambioPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CResolucionPedimentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoFuncionarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CActividadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAreaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstudioPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPedimentoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAdministrativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDepartamentoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionGeneralDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDivisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPresupuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProgramaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSeccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCantonDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProvinciaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatPermisoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CClaseDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCuentaBancariaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleContratacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadFinancieraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesgloseSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetallePuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPeriodoEscalaSalarialDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.COcupacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CSubEspecialidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroTiempoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDireccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDistritoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHistorialEstadoCivilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncentivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CInformacionContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoContactoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoMovimientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoMovimientoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPerfilAccesoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPresupuestoExtraDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRelPuestoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoUbicacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoJornadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionRealDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CErrorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRespuestaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadSegurosDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMontoCaucionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFormacionAcademicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoCapacitacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadEducativaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CModalidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCursoGradoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContenidoPresupuestarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadAdscritaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadGubernamentalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAddendumPrestamoPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCaracteristicasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTituloFactorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTareasPuestoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRescisionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoExtraordinarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDeduccionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoDiaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CUbicacionAsuetoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CPagoFeriadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDeduccionEfectuadaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDiaPagadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoTramiteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoRemuneracionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRemuneracionEfectuadaPFDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEmpleadoDispositivoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMotivoBajaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CContratoArrendamientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CFacturaDesarraigoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCartaPresentacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CHorarioRangoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMarcacionesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEntidadMedicaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CRegistroIncapacidadDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleCalificacionNombramientoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleEvaluacionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CCatalogoPreguntaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDatosGeneralesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CProcAlmacenadoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CTipoAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoBorradorAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoBorradorDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalHistoricoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CAccionPersonalDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CEstadoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleDeduccionViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CMovimientoViaticoCorridoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CDetalleAsignacionGastoTransporteDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBitacoraUsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SIRH.DTO.CBorradorAccionPersonalDTO))]
        SIRH.DTO.CBaseDTO ActualizarEstado(SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CMovimientoBorradorAccionPersonalDTO movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/ActualizarEstado", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/ActualizarEstadoResponse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> ActualizarEstadoAsync(SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CMovimientoBorradorAccionPersonalDTO movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/FuncionariosConBorradores", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/FuncionariosConBorradoresRespo" +
            "nse")]
        SIRH.DTO.CBaseDTO[][] FuncionariosConBorradores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICBorradorAccionPersonalService/FuncionariosConBorradores", ReplyAction="http://tempuri.org/ICBorradorAccionPersonalService/FuncionariosConBorradoresRespo" +
            "nse")]
        System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> FuncionariosConBorradoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICBorradorAccionPersonalServiceChannel : SIRH.Web.BorradorAccionPersonalLocal.ICBorradorAccionPersonalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CBorradorAccionPersonalServiceClient : System.ServiceModel.ClientBase<SIRH.Web.BorradorAccionPersonalLocal.ICBorradorAccionPersonalService>, SIRH.Web.BorradorAccionPersonalLocal.ICBorradorAccionPersonalService {
        
        public CBorradorAccionPersonalServiceClient() {
        }
        
        public CBorradorAccionPersonalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CBorradorAccionPersonalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CBorradorAccionPersonalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CBorradorAccionPersonalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIRH.DTO.CBaseDTO GuardarSolicitud(SIRH.DTO.CBorradorAccionPersonalDTO registro, string codUsuarioEnvia, string codUsuarioRecibe) {
            return base.Channel.GuardarSolicitud(registro, codUsuarioEnvia, codUsuarioRecibe);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> GuardarSolicitudAsync(SIRH.DTO.CBorradorAccionPersonalDTO registro, string codUsuarioEnvia, string codUsuarioRecibe) {
            return base.Channel.GuardarSolicitudAsync(registro, codUsuarioEnvia, codUsuarioRecibe);
        }
        
        public SIRH.DTO.CBaseDTO GuardarBorrador(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CEstadoBorradorDTO estado, SIRH.DTO.CTipoAccionPersonalDTO tipo, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, string codUsuarioEnvia, string codUsuarioRecibe) {
            return base.Channel.GuardarBorrador(funcionario, estado, tipo, registro, detalle, codUsuarioEnvia, codUsuarioRecibe);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> GuardarBorradorAsync(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CEstadoBorradorDTO estado, SIRH.DTO.CTipoAccionPersonalDTO tipo, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, string codUsuarioEnvia, string codUsuarioRecibe) {
            return base.Channel.GuardarBorradorAsync(funcionario, estado, tipo, registro, detalle, codUsuarioEnvia, codUsuarioRecibe);
        }
        
        public SIRH.DTO.CBaseDTO EditarBorrador(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CEstadoBorradorDTO estado, SIRH.DTO.CTipoAccionPersonalDTO tipo, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, SIRH.DTO.CMovimientoBorradorAccionPersonalDTO movimiento) {
            return base.Channel.EditarBorrador(funcionario, estado, tipo, registro, detalle, movimiento);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> EditarBorradorAsync(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CEstadoBorradorDTO estado, SIRH.DTO.CTipoAccionPersonalDTO tipo, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, SIRH.DTO.CMovimientoBorradorAccionPersonalDTO movimiento) {
            return base.Channel.EditarBorradorAsync(funcionario, estado, tipo, registro, detalle, movimiento);
        }
        
        public SIRH.DTO.CBaseDTO[] ObtenerBorrador(int codigo) {
            return base.Channel.ObtenerBorrador(codigo);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[]> ObtenerBorradorAsync(int codigo) {
            return base.Channel.ObtenerBorradorAsync(codigo);
        }
        
        public SIRH.DTO.CBaseDTO[][] BuscarSolicitud(SIRH.DTO.CBorradorAccionPersonalDTO registro) {
            return base.Channel.BuscarSolicitud(registro);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarSolicitudAsync(SIRH.DTO.CBorradorAccionPersonalDTO registro) {
            return base.Channel.BuscarSolicitudAsync(registro);
        }
        
        public SIRH.DTO.CBaseDTO[][] BuscarBorrador(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, System.DateTime[] fechasRige, System.DateTime[] fechasVence) {
            return base.Channel.BuscarBorrador(funcionario, registro, detalle, fechasRige, fechasVence);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> BuscarBorradorAsync(SIRH.DTO.CFuncionarioDTO funcionario, SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CDetalleBorradorAccionPersonalDTO detalle, System.DateTime[] fechasRige, System.DateTime[] fechasVence) {
            return base.Channel.BuscarBorradorAsync(funcionario, registro, detalle, fechasRige, fechasVence);
        }
        
        public SIRH.DTO.CBaseDTO ActualizarEstado(SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CMovimientoBorradorAccionPersonalDTO movimiento) {
            return base.Channel.ActualizarEstado(registro, movimiento);
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO> ActualizarEstadoAsync(SIRH.DTO.CBorradorAccionPersonalDTO registro, SIRH.DTO.CMovimientoBorradorAccionPersonalDTO movimiento) {
            return base.Channel.ActualizarEstadoAsync(registro, movimiento);
        }
        
        public SIRH.DTO.CBaseDTO[][] FuncionariosConBorradores() {
            return base.Channel.FuncionariosConBorradores();
        }
        
        public System.Threading.Tasks.Task<SIRH.DTO.CBaseDTO[][]> FuncionariosConBorradoresAsync() {
            return base.Channel.FuncionariosConBorradoresAsync();
        }
    }
}
